# Assignment 2B — RAG Pipeline (Manufacturing & Technical Standards)

**Course:** Large Language Models for Generative AI (S1-26_AIMLZG536)  

**Assignment Group:** Group ID 78
### Student Details and Team Contribution

| Field | Details |
|-------|---------|
| **Assignment** | Assignment-2B RAG Pipeline (Manufacturing & Technical Standards) |
| **Course** | CourseLarge Language Models for Generative AI (S1-26_AIMLZG536) |
| **Assessment** | EC-1 |
| **Submission Date** | *(Fill in date)* |

<br>
Below is the Team member details and their contributions to the assignment
<br></br>

| Member | BITS ID | Assigned Tasks and Contribution Areas |
|--------|---------|----------------------------------------|
| RAJESH R. SHENOI | 2025AE05200 |  ?? |
| THEJUS AUGUSTINE JOSE | 2025AF05140 |  ?? |
| VIJAY KUMAR PRAJAPAT | 2025AE05719 |  ?? |
| VIJETH MOUDGALYA V | 2025AE05358 |  ?? |

Builds a small, complete Retrieval-Augmented Generation (RAG) system on the Assignment 1 domain corpus:

```
12 cleaned .txt docs ──► chunk ──► embed ──► FAISS (dense) ─┐
                              |                             |
                              └──► BM25 (keyword) ──────────┼─► RRF hybrid ─► cross-encoder rerank ─► top-3 chunks
                                                                                                          │
                         Assignment 1 model (TinyLlama-1.1B + QLoRA Adapter B) ◄── grounded prompt ◄──────┘
                                         │
                                         └──► LLM judge (correct? supported?)
```

| Part | What we do? | Marks |
|---|---|---|
| A | Dense search + choose a chunk size | 5 |
| B | Dense vs BM25 vs Hybrid (RRF) | 4 |
| C | Cross-encoder reranking | 4 |
| D | Grounded generation + LLM judge | 7 |

**Reused from Assignment 1:**
1) the 12 cleaned domain `.txt` files
2) the 10-pair evaluation set (`eval_dataset.jsonl`, seed-42 split) and
3) the fine-tuned TinyLlama-1.1B + QLoRA Adapter B

**Models actually used in Part D:** the Assignment 1 model ignored the chunks (no citations, no "Not found"), so — as the brief allows — the final answers come from `microsoft/Phi-3.5-mini-instruct`; the judge is `Qwen/Qwen2.5-7B-Instruct`.

---
## Step 0 — Environment setup
Parts A–C run on CPU or GPU. Part D loads LLMs and needs a GPU (Prayogshala / Colab).

In [14]:
%pip install -q sentence-transformers faiss-cpu rank_bm25

In [15]:
import os, re, json, time, random, textwrap
from pathlib import Path

import numpy as np
import pandas as pd
import torch

random.seed(42); np.random.seed(42); torch.manual_seed(42)
pd.set_option("display.max_colwidth", 120)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE, "|", torch.cuda.get_device_name(0) if DEVICE == "cuda" else "CPU only")

# Find the corpus folder whichever platform we are on
CANDIDATES = [Path("domain_corpus"), Path("/home/jovyan/domain_corpus"), Path("/content/domain_corpus")]
CORPUS_DIR = next((p for p in CANDIDATES if p.exists() and any(p.glob("*.txt"))), None)
assert CORPUS_DIR is not None, "Upload the 12 cleaned .txt files into a folder named domain_corpus/"
print("Corpus folder:", CORPUS_DIR.resolve())

Device: cuda | Tesla T4
Corpus folder: /content/domain_corpus

In [16]:
# Google Drive is only needed on Colab (it holds the Assignment 1 adapter); on Prayogshala everything is local
try:
    from google.colab import drive
    drive.mount('/content/drive')
except ImportError:
    print("Not running on Colab - skipping the Google Drive mount")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
import os
from pathlib import Path

# Create the domain_corpus directory if it doesn't exist
corpus_path = Path('domain_corpus')
corpus_path.mkdir(exist_ok=True)
print(f"Folder '{corpus_path.resolve()}' is ready. Please upload your 12 cleaned .txt files here.")

Folder '/content/domain_corpus' is ready. Please upload your 12 cleaned .txt files here.

### 0.1 Load the document collection
We reuse the cleaned Assignment 1 (12 *.txt) files as-is. Only whitespace is collapsed — we deliberately do **not** fix the OCR noise (e.g. `management-ied`, `weii`) because real RAG systems must cope with imperfect text, and the answer spans below are
copied verbatim from this text.

In [18]:
def normalize_ws(text: str) -> str:
    # Collapse all runs of whitespace (newlines, tabs, double spaces) to a single space.
    return re.sub(r"\s+", " ", text).strip()

docs = {p.name: normalize_ws(p.read_text(encoding="utf-8", errors="ignore"))
        for p in sorted(CORPUS_DIR.glob("*.txt"))}

corpus_stats = pd.DataFrame([{"document": n, "characters": len(t), "words": len(t.split())} for n, t in docs.items()])
print(f"{len(docs)} documents | {corpus_stats.characters.sum():,} characters | {corpus_stats.words.sum():,} words")
corpus_stats

12 documents | 2,448,363 characters | 426,339 words

                                        document  characters   words
0               NIST_ISO9000_Quality_Systems.txt       48600    7533
1              NIST_Malcolm_Baldrige_Quality.txt       39432    6001
2                NIST_Manufacturing_Handbook.txt     1092303  210709
3   NIST_Manufacturing_Machinery_Maintenance.txt      113122   17206
4               NIST_Measurement_Uncertainty.txt       87256   14294
5     NIST_QIF_Quality_Information_Framework.txt       74356   10408
6       NIST_Quality_Assurance_Manufacturing.txt       38236    5552
7              NIST_Quality_Systems_Handbook.txt      124549   20636
8                  OSHA_Ergonomics_Workplace.txt       31772    5484
9            OSHA_General_Industry_Standards.txt      539628   88902
10           OSHA_Machine_Guarding_Standards.txt      174658   27520
11             OSHA_Safety_Health_Management.txt       84451   12094

### 0.2 The 10 evaluation queries and their answer spans
The queries and expected answers are the 10-pair evaluation split from Assignment 1 (48 curated pairs, 80/20 split, `random.seed(42)`).

**Answer span** = the sentence or short passage in the corpus that answers the query. A retrieved chunk is a **hit** if it contains the span.
Each span was found by searching the query's source document and copied verbatim (OCR errors included). Spans are kept short
(13–27 tokens) so that each one can fit inside even a 100-token chunk.

In [19]:
EVAL = [
 {"qid": 1, "source": "NIST_Malcolm_Baldrige_Quality.txt",
  "query": "How did Malcolm Baldrige quality concepts influence the STEP model qualification approach?",
  "expected": "The STEP qualification effort used several ideas drawn from the Malcolm Baldrige National Quality Award criteria. These ideas encouraged measurable quality thresholds, links between processes and results, continuous improvement, comparison with established performance levels, and management involvement in producing high-quality information models.",
  "span": "Many basic concepts of the Malcolm Baldrige National Quality Award were used in building the foundation for this new approach to standards development"},
 {"qid": 2, "source": "OSHA_Ergonomics_Workplace.txt",
  "query": "How can workstation design reduce excessive reaching and awkward upper-body posture?",
  "expected": "Workstations can be arranged so materials and products are positioned closer to workers. Examples include conveyor diverters, appropriately located chutes or cut-outs, and correctly adjusted work platforms. These changes can reduce long reaches, elevated arms, wrist deviation, forward bending, and other stressful postures.",
  "span": "This conveyor has diverters in place that push the products closer to the workers. This reduces reaches for the employees."},
 {"qid": 3, "source": "NIST_Malcolm_Baldrige_Quality.txt",
  "query": "What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the report?",
  "expected": "The report describes results as being assessed through improvement trends, current performance levels, and benchmarks or other comparisons with external performance. Together these forms of evidence show whether quality is improving, what level has been reached, and how performance compares with appropriate leaders.",
  "span": "based upon one or more of three factors: (1) improvement trends; (2) current levels; and (3) benchmarks"},
 {"qid": 4, "source": "NIST_Manufacturing_Handbook.txt",
  "query": "Why are statistical methods useful when analysing manufacturing experiments?",
  "expected": "Statistical methods provide a systematic way to summarize experimental observations, describe the amount of variation in measured results, and judge whether apparent differences are meaningful. This helps manufacturing engineers draw conclusions from data rather than relying only on individual observations or subjective impressions.",
  "span": "One of the most frequent uses of statistics is in testing for differences."},
 {"qid": 5, "source": "NIST_Manufacturing_Machinery_Maintenance.txt",
  "query": "What is the difference between reactive maintenance and more advanced maintenance strategies?",
  "expected": "Reactive maintenance responds after machinery has already failed or developed a problem. Preventive and predictive approaches attempt to reduce failures by maintaining equipment before breakdowns occur or by using information about equipment condition to guide maintenance decisions, thereby reducing avoidable downtime and production losses.",
  "span": "is maintenance done, typically, after equipment has failed to produce a product within desired quality or production targets"},
 {"qid": 6, "source": "NIST_Manufacturing_Machinery_Maintenance.txt",
  "query": "What costs are included when analysing direct and indirect machinery-maintenance impacts?",
  "expected": "Direct maintenance costs include labour and materials used for maintenance and repair. The broader economic analysis also considers cascading damage following breakdowns, inventory increases caused by uncertainty or disruption, unplanned downtime, defects, lost sales, and other losses associated with faults and failures.",
  "span": "Direct maintenance and repair costs include the cost of labor and materials along with cascading effects"},
 {"qid": 7, "source": "NIST_Measurement_Uncertainty.txt",
  "query": "What is the difference between Type A and Type B evaluations of uncertainty?",
  "expected": "A Type A evaluation determines an uncertainty component through statistical analysis of repeated observations. A Type B evaluation uses other available information, such as calibration data, previous measurements, instrument specifications, reference data, or scientific judgement, rather than relying on repeated statistical observations alone.",
  "span": "The evaluation of uncertainty by the statistical analysis of series of observations is termed a Type A evaluation"},
 {"qid": 8, "source": "NIST_ISO9000_Quality_Systems.txt",
  "query": "What common elements are included in the ISO 9001, ISO 9002, and ISO 9003 quality-system models?",
  "expected": "The ISO 9000 quality-system models share requirements for an effective quality system, valid measurements, regularly calibrated measuring and testing equipment, suitable statistical techniques, product identification and traceability, adequate records, inspection and testing, proper handling and storage, and control of nonconforming items.",
  "span": "Common elements in ISO 9001, 9002, and 9003 include the need for; an effective quality system"},
 {"qid": 9, "source": "NIST_Malcolm_Baldrige_Quality.txt",
  "query": "Why is management involvement important in a quality-improvement program?",
  "expected": "The report emphasizes that successful quality improvement should be management-led and customer-oriented. Management establishes expectations, provides direction and resources, supports the use of quality metrics and thresholds, and creates the organizational conditions needed for persistent, systematic improvement rather than isolated corrective actions.",
  "span": "quality improvement programs must be management-ied and customer-oriented"},
 {"qid": 10, "source": "OSHA_Machine_Guarding_Standards.txt",
  "query": "What is the main purpose of machine guarding?",
  "expected": "Machine guarding protects operators and other employees from hazards created by moving machine parts and operations. Safeguards are intended to prevent workers from reaching dangerous areas such as points of operation, rotating components, nip points, and other locations where cutting, crushing, or entanglement injuries could occur.",
  "span": "Safeguarding is essential for protecting employees from needless and preventable injury."},
]
QUERIES = [e["query"] for e in EVAL]

# Hit test used in Parts A, B and C: case- and whitespace-insensitive substring match
def norm(s: str) -> str:
    return normalize_ws(s).lower()

def is_hit(chunk_text: str, span: str) -> bool:
    return norm(span) in norm(chunk_text)

# Sanity check: every span must exist (exactly once) in its source document
for e in EVAL:
    n = norm(docs[e["source"]]).count(norm(e["span"]))
    assert n >= 1, f"Q{e['qid']}: span not found in {e['source']}"
    e["span_occurrences"] = n

pd.DataFrame(EVAL)[["qid", "query", "source", "span", "span_occurrences"]]

,qid,query,source,span,span_occurrences
0,1,How did Malcolm Baldrige quality concepts influence the STEP model qualification approach?,NIST_Malcolm_Baldrige_Quality.txt,Many basic concepts of the Malcolm Baldrige National Quality Award were used in building the foundation for this new...,1
1,2,How can workstation design reduce excessive reaching and awkward upper-body posture?,OSHA_Ergonomics_Workplace.txt,This conveyor has diverters in place that push the products closer to the workers. This reduces reaches for the empl...,1
2,3,What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the rep...,NIST_Malcolm_Baldrige_Quality.txt,based upon one or more of three factors: (1) improvement trends; (2) current levels; and (3) benchmarks,1
3,4,Why are statistical methods useful when analysing manufacturing experiments?,NIST_Manufacturing_Handbook.txt,One of the most frequent uses of statistics is in testing for differences.,1
4,5,What is the difference between reactive maintenance and more advanced maintenance strategies?,NIST_Manufacturing_Machinery_Maintenance.txt,"is maintenance done, typically, after equipment has failed to produce a product within desired quality or production...",1
5,6,What costs are included when analysing direct and indirect machinery-maintenance impacts?,NIST_Manufacturing_Machinery_Maintenance.txt,Direct maintenance and repair costs include the cost of labor and materials along with cascading effects,1
6,7,What is the difference between Type A and Type B evaluations of uncertainty?,NIST_Measurement_Uncertainty.txt,The evaluation of uncertainty by the statistical analysis of series of observations is termed a Type A evaluation,1
7,8,"What common elements are included in the ISO 9001, ISO 9002, and ISO 9003 quality-system models?",NIST_ISO9000_Quality_Systems.txt,"Common elements in ISO 9001, 9002, and 9003 include the need for; an effective quality system",1
8,9,Why is management involvement important in a quality-improvement program?,NIST_Malcolm_Baldrige_Quality.txt,quality improvement programs must be management-ied and customer-oriented,1
9,10,What is the main purpose of machine guarding?,OSHA_Machine_Guarding_Standards.txt,Safeguarding is essential for protecting employees from needless and preventable injury.,1

---
# Part A — Dense search and chunk size (5 marks)

**Dense retrieval in one paragraph.** An embedding model maps any text to a fixed-length vector so that texts with similar
*meaning* land close together. We embed every chunk once (offline), store the vectors in an index, and at query time embed the
query and return the chunks whose vectors are most similar. If all vectors are L2-normalised, the inner product equals cosine
similarity, so a FAISS `IndexFlatIP` (exact, brute-force inner-product search) gives exact cosine-similarity search.

### Embedding model choice and its input limit
The assignment asks for chunk sizes of 100 and 400 tokens. `all-MiniLM-L6-v2` truncates input at **256** tokens, so a
400-token chunk would lose its last ~144 tokens when embedded (they would still be sent to the LLM, but would be invisible to search).
**We therefore switched to a model with a longer limit: `BAAI/bge-small-en-v1.5`** — 512-token limit, 384-dim vectors,
33M parameters, so it is just as cheap to run. Tokens are counted with this model's own tokenizer.

BGE models are trained with an instruction prefix for short queries
(`"Represent this sentence for searching relevant passages: "`); passages are embedded without it.

In [20]:
from sentence_transformers import SentenceTransformer
import faiss

EMBED_MODEL_ID = "BAAI/bge-small-en-v1.5"
QUERY_PREFIX   = "Represent this sentence for searching relevant passages: "
EMBED_BATCH    = 64

embedder  = SentenceTransformer(EMBED_MODEL_ID, device=DEVICE)
tokenizer = embedder.tokenizer
MAX_TOKENS = embedder.max_seq_length            # limit applied when embedding (incl. [CLS]/[SEP])
EMBED_DIM  = (embedder.get_embedding_dimension() if hasattr(embedder, "get_embedding_dimension")
              else embedder.get_sentence_embedding_dimension())

print("Embedding model :", EMBED_MODEL_ID)
print("Max input length:", MAX_TOKENS, "tokens")
print("Vector size     :", EMBED_DIM)

def count_tokens(text: str) -> int:
    return len(tokenizer(text, add_special_tokens=False)["input_ids"])

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  133MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model : BAAI/bge-small-en-v1.5
Max input length: 512 tokens
Vector size     : 384

## A1. Build dense search (2 marks)

### A1.1 — One reusable dense-search component
`DenseIndex` embeds a list of chunks, builds a FAISS `IndexFlatIP`, and `search(query, k)` returns the top-k chunks with scores.
The same class is reused for every chunk size in A2 and again in Parts B and C.

In [21]:
class DenseIndex:
    # Embed chunks -> FAISS IndexFlatIP (cosine via normalised vectors) -> top-k search.

    def __init__(self, chunks, model=embedder, batch_size=EMBED_BATCH, query_prefix=QUERY_PREFIX):
        self.chunks, self.model, self.batch_size, self.query_prefix = chunks, model, batch_size, query_prefix
        texts = [c["text"] for c in chunks]

        t0 = time.perf_counter()
        vecs = model.encode(texts, batch_size=batch_size, normalize_embeddings=True,
                            convert_to_numpy=True, show_progress_bar=False).astype("float32")
        t1 = time.perf_counter()
        self.index = faiss.IndexFlatIP(vecs.shape[1])
        self.index.add(vecs)
        t2 = time.perf_counter()

        self.embed_seconds, self.add_seconds = t1 - t0, t2 - t1
        self.build_seconds = t2 - t0

    def search(self, query: str, k: int = 5):
        q = self.model.encode([self.query_prefix + query], normalize_embeddings=True,
                              convert_to_numpy=True).astype("float32")
        scores, ids = self.index.search(q, k)
        return [{**self.chunks[i], "score": float(s), "rank": r}
                for r, (i, s) in enumerate(zip(ids[0], scores[0]), start=1)]

## A2. Choose a chunk size (3 marks)

### Fixed-size chunking with the embedding model's tokenizer
Each document is tokenized once with `return_offsets_mapping=True`. That gives, for every token, its character position in the
original text, so a window of N tokens can be cut directly from the **original** text (no decode step, so casing and
punctuation are preserved). Chunks never cross document boundaries, and there is no overlap, as the assignment specifies.

Both sizes fit the model: 100 + 2 and 400 + 2 special tokens are ≤ 512, so nothing is truncated.

In [22]:
def chunk_fixed(docs: dict, size: int):
    # Split every document into consecutive, non-overlapping windows of `size` tokens.
    chunks = []
    for name, text in docs.items():
        enc = tokenizer(text, add_special_tokens=False, return_offsets_mapping=True, verbose=False)
        offsets = enc["offset_mapping"]
        for start in range(0, len(offsets), size):
            window = offsets[start:start + size]
            chunks.append({
                "chunk_id": len(chunks),
                "doc": name,
                "text": text[window[0][0]:window[-1][1]],
                "n_tokens": len(window),
            })
    return chunks

CHUNK_SIZES = [100, 400]
chunk_sets = {size: chunk_fixed(docs, size) for size in CHUNK_SIZES}

for size, chunks in chunk_sets.items():
    assert max(c["n_tokens"] for c in chunks) + 2 <= MAX_TOKENS
    print(f"{size:>3}-token chunks: {len(chunks):>5} chunks | example from {chunks[1]['doc']}:")
    print(textwrap.indent(textwrap.fill(chunks[1]["text"][:300] + " ...", 110), "    "))

100-token chunks:  6386 chunks | example from NIST_ISO9000_Quality_Systems.txt:
    COMMERCE Robert A. Mosbacher, Secretary NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY John W. Lyons, Director
    NIST NISTIR 4721 Questions and Answers on Quality, the ISO 9000 Standard Series, Quality System Registration,
    and Related Issues Maureen Breitenberg U.S. DEPARTMENT OF COMMERCE National Ins ...
400-token chunks:  1601 chunks | example from NIST_ISO9000_Quality_Systems.txt:
    s Office of European Community Affairs; Mr. Charles Hyer, the Marley Organization; Mr. Donald Mackay, Air-
    Conditioning and Refrigeration Institute; Dr. Curt Reimann and Dr. Robert Chapman, NIST's Office of Quality
    Programs; Patricia Kopp, American Society for Quality Control; and NIST's Standards C ...

**Can every span be found at each size?** With no overlap, a span that happens to straddle a chunk boundary is split in two,
and *no* chunk can ever contain it. Checking this up front tells us the best hit rate each chunk size could possibly reach.

In [23]:
reachable = pd.DataFrame({
    f"{size} tokens": ["yes" if any(is_hit(c["text"], e["span"]) for c in chunks) else "SPLIT"
                       for e in EVAL]
    for size, chunks in chunk_sets.items()
}, index=[f"Q{e['qid']}" for e in EVAL])
print("Span contained intact in at least one chunk:")
reachable.T

Span contained intact in at least one chunk:

             Q1     Q2   Q3   Q4     Q5   Q6   Q7   Q8   Q9  Q10
100 tokens  yes  SPLIT  yes  yes  SPLIT  yes  yes  yes  yes  yes
400 tokens  yes    yes  yes  yes    yes  yes  yes  yes  yes  yes

### A2.1 — Dense search at 100 vs 400 tokens (2 marks)
For each size: build the dense index (A1), retrieve the top 3 for each of the 10 queries, and compute
* **Hit rate@3** — share of queries where one of the top-3 chunks contains the answer span
* **Tokens sent per query** — combined token count of the top-3 chunks, averaged over the 10 queries

In [24]:
from transformers import AutoTokenizer

# The generator (Assignment 1 TinyLlama) uses a different tokenizer from the embedder, so count its tokens too
GEN_MODEL_ID  = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
gen_tokenizer = AutoTokenizer.from_pretrained(GEN_MODEL_ID)

def count_gen_tokens(text: str) -> int:
    return len(gen_tokenizer(text, add_special_tokens=False)["input_ids"])

def hit_at_k(results, span, k):
    return any(is_hit(r["text"], span) for r in results[:k])

dense_indexes, a2_rows, a2_detail = {}, [], []
for size, chunks in chunk_sets.items():
    idx = DenseIndex(chunks)
    dense_indexes[size] = idx
    hits, tokens_sent, gen_tokens_sent = [], [], []
    for e in EVAL:
        top3 = idx.search(e["query"], k=3)
        hit_rank = next((r["rank"] for r in top3 if is_hit(r["text"], e["span"])), None)
        hits.append(hit_rank is not None)
        tokens_sent.append(sum(r["n_tokens"] for r in top3))
        gen_tokens_sent.append(sum(count_gen_tokens(r["text"]) for r in top3))
        a2_detail.append({"chunk size": size, "qid": e["qid"], "hit rank (top 3)": hit_rank or "-",
                          "top-1 doc": top3[0]["doc"], "correct doc": e["source"]})
    a2_rows.append({"Chunk size (tokens)": size,
                    "Total chunks": len(chunks),
                    "Hit rate@3 (%)": 100 * np.mean(hits),
                    "Tokens sent per query (top 3)": round(np.mean(tokens_sent), 1),
                    "TinyLlama tokens per query (avg)": round(np.mean(gen_tokens_sent), 1),
                    "TinyLlama tokens per query (max)": max(gen_tokens_sent),
                    "Index build time (s)": round(idx.build_seconds, 2)})

a2_table = pd.DataFrame(a2_rows)
a2_table

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

tokenizer.model: reconstructing file:   0%|          |  0.00B /  500kB

tokenizer.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

,Chunk size (tokens),Total chunks,Hit rate@3 (%),Tokens sent per query (top 3),TinyLlama tokens per query (avg),TinyLlama tokens per query (max),Index build time (s)
0,100,6386,60.0,300.0,358.0,418,12.30
1,400,1601,60.0,1200.0,1443.1,1831,13.66

In [25]:
# Per-query view: which queries hit, and at what rank? Did the top-1 chunk even come from the right document?
pd.DataFrame(a2_detail).pivot(index="qid", columns="chunk size", values=["hit rank (top 3)", "top-1 doc"])

           hit rank (top 3)                                         top-1 doc  \
chunk size              100 400                                           100
qid
1                         2   -             NIST_Malcolm_Baldrige_Quality.txt
2                         -   3                 OSHA_Ergonomics_Workplace.txt
3                         2   2             NIST_Malcolm_Baldrige_Quality.txt
4                         3   -               NIST_Manufacturing_Handbook.txt
5                         -   -  NIST_Manufacturing_Machinery_Maintenance.txt
6                         1   2  NIST_Manufacturing_Machinery_Maintenance.txt
7                         -   3              NIST_Measurement_Uncertainty.txt
8                         1   2              NIST_ISO9000_Quality_Systems.txt
9                         1   3             NIST_Malcolm_Baldrige_Quality.txt
10                        -   -           OSHA_Machine_Guarding_Standards.txt


chunk size                                           400
qid
1                      NIST_Malcolm_Baldrige_Quality.txt
2                          OSHA_Ergonomics_Workplace.txt
3                      NIST_Malcolm_Baldrige_Quality.txt
4                        NIST_Manufacturing_Handbook.txt
5           NIST_Manufacturing_Machinery_Maintenance.txt
6           NIST_Manufacturing_Machinery_Maintenance.txt
7                       NIST_Measurement_Uncertainty.txt
8                       NIST_ISO9000_Quality_Systems.txt
9                    OSHA_General_Industry_Standards.txt
10                   OSHA_Machine_Guarding_Standards.txt

**Observations from the A2 results**
* **Same hit rate@3 (60%), different queries.** 100-token chunks hit Q1, Q3, Q4, Q6, Q8, Q9; 400-token chunks hit Q2, Q3, Q6, Q7, Q8, Q9.
  Q2 is only reachable at 400 (its span is split at 100); Q7 needs the longer window.
* **Rank 1 is better with small chunks** — 3/10 at 100 tokens (Q6, Q8, Q9) vs 0/10 at 400. A small chunk's embedding is
  dominated by the answer sentence; a 400-token chunk mixes several topics, so its vector is "diluted" and lands at rank 2–3.
* **Right document, wrong passage.** Q5 and Q10 are missed at both sizes, yet the top-1 chunk comes from the correct document
  for 10/10 queries at 100 tokens and 9/10 at 400. Dense search finds the right *area*; the problem is ranking *within* it —
  exactly what hybrid search (Part B) and reranking (Part C) target.
* **Build time is about equal (12.5 s vs 13.5 s)** even though 100-token chunks are 4× more numerous: the total number of tokens embedded
  is the same (~640k), only packed into more, shorter sequences.
* **Tokenizers differ.** One BGE token ≈ 1.25 TinyLlama tokens on this corpus (OCR noise and numbers split into many pieces),
  so "1,200 tokens" for the embedder is ~1,500 for the generator.

### A2.2 — Chosen chunk size (1 mark)
**We use 400-token chunks for Parts B–D.** Both sizes reach the same hit rate@3 (60%), but at 100 tokens the answer spans of
Q2 and Q5 are cut across chunk boundaries, capping that size at 80%, while every span stays intact at 400 tokens and each
chunk carries enough surrounding text for multi-part answers. The cost is 4× more context — about 1,200 embedding tokens
(≈1,500 TinyLlama tokens) per query — which still fits TinyLlama's 2,048-token window next to a short prompt and a
~250-token answer; unusually long OCR-heavy chunks are trimmed by a token budget in Part D, and the weaker rank-1 accuracy
of large chunks (0/10 vs 3/10) is what reranking in Part C should recover.

In [26]:
CHOSEN_SIZE = 400

TINYLLAMA_CONTEXT     = 2048
PROMPT_ANSWER_BUDGET  = 150 + 250    # instructions + question, plus the generated answer
row = a2_table.set_index("Chunk size (tokens)").loc[CHOSEN_SIZE]

print(f"Chosen chunk size: {CHOSEN_SIZE} tokens")
for label, n in [("average", row["TinyLlama tokens per query (avg)"]), ("worst ", row["TinyLlama tokens per query (max)"])]:
    total = n + PROMPT_ANSWER_BUDGET
    print(f"  {label} query: {n:>6.0f} context + {PROMPT_ANSWER_BUDGET} prompt/answer = {total:>6.0f} TinyLlama tokens "
          f"({100 * total / TINYLLAMA_CONTEXT:.0f}% of {TINYLLAMA_CONTEXT}) -> {'fits' if total <= TINYLLAMA_CONTEXT else 'needs trimming in Part D'}")

CHUNKS = chunk_sets[CHOSEN_SIZE]
dense  = dense_indexes[CHOSEN_SIZE]

Chosen chunk size: 400 tokens
  average query:   1443 context + 400 prompt/answer =   1843 TinyLlama tokens (90% of 2048) -> fits
  worst  query:   1831 context + 400 prompt/answer =   2231 TinyLlama tokens (109% of 2048) -> needs trimming in Part D

### A1.2 — Dense search report for the final chunk set (1 mark)

In [27]:
a1_report = pd.DataFrame([
    ("Embedding model", EMBED_MODEL_ID),
    ("Max input length (tokens)", MAX_TOKENS),
    ("Vector size", EMBED_DIM),
    ("Similarity measure", "Cosine similarity (L2-normalised vectors + inner product, FAISS IndexFlatIP, exact search)"),
    ("Batch size", EMBED_BATCH),
    ("Device", DEVICE),
    ("Final chunk set", f"{CHOSEN_SIZE}-token fixed chunks, no overlap, {len(CHUNKS):,} chunks"),
    ("Index build time (s)", f"{dense.build_seconds:.2f}  (embedding {dense.embed_seconds:.2f} + index add {dense.add_seconds:.4f})"),
], columns=["Item", "Value"])
a1_report

,Item,Value
0,Embedding model,BAAI/bge-small-en-v1.5
1,Max input length (tokens),512
2,Vector size,384
3,Similarity measure,"Cosine similarity (L2-normalised vectors + inner product, FAISS IndexFlatIP, exact search)"
4,Batch size,64
5,Device,cuda
6,Final chunk set,"400-token fixed chunks, no overlap, 1,601 chunks"
7,Index build time (s),13.66 (embedding 13.66 + index add 0.0004)

> **Observation:** almost all of the build time is spent *embedding* the chunks (a forward pass of the model per chunk);
> adding vectors to a flat FAISS index is just a memory copy. The flat index is exact; at this corpus size (a few thousand
> vectors) approximate indexes such as HNSW or IVF are unnecessary.

---
# Part B — Keyword and hybrid search (4 marks)

All three methods search the same 1,601 × 400-token chunks, return the **top 5**, and are scored on the same 10 queries.

| Method | Matches on | Strong when | Weak when |
|---|---|---|---|
| **Dense** (BGE + FAISS) | meaning (vectors) | the query paraphrases the text ("awkward posture" ≈ "bending and reaching") | exact names, numbers, codes; diluted long chunks |
| **BM25** (keywords) | exact word overlap, weighted by rarity | rare, specific terms ("Type A", "ISO 9002", "cascading") | synonyms, paraphrases, OCR-mangled words |
| **Hybrid (RRF)** | ranks from both lists | the two methods make *different* mistakes | both methods miss the same chunk |

### Shared evaluation harness
`evaluate()` runs one warm-up query (not timed), then times each of the 10 queries end-to-end (query in → top 5 out) and
records the rank of the first chunk that contains the answer span.

In [28]:
TOP_K = 5

def first_hit_rank(results, span):
    return next((r["rank"] for r in results if is_hit(r["text"], span)), None)

def evaluate(search_fn, k=TOP_K):
    search_fn(QUERIES[0], k)                                   # warm-up run, not timed
    per_query, latencies = [], []
    for e in EVAL:
        t0 = time.perf_counter()
        results = search_fn(e["query"], k)
        latencies.append((time.perf_counter() - t0) * 1000)
        per_query.append({"qid": e["qid"], "hit_rank": first_hit_rank(results, e["span"]), "results": results})
    ranks = [p["hit_rank"] for p in per_query]
    pct = lambda flags: round(100 * float(np.mean(flags)), 1)
    summary = {"Average query latency (ms)": round(float(np.mean(latencies)), 2),
               "Hit rate@1 (%)": pct([r == 1 for r in ranks]),
               "Hit rate@3 (%)": pct([r is not None and r <= 3 for r in ranks]),
               "Hit rate@5 (%)": pct([r is not None for r in ranks])}
    return summary, per_query

b_summary, b_per_query = {}, {}

## B1. Dense (1 mark)
The Part A index, unchanged, now asked for the top 5.

In [29]:
def dense_search(query, k=TOP_K):
    return dense.search(query, k)

b_summary["Dense"], b_per_query["Dense"] = evaluate(dense_search)
b_summary["Dense"]

{'Average query latency (ms)': 11.86,
 'Hit rate@1 (%)': 0.0,
 'Hit rate@3 (%)': 60.0,
 'Hit rate@5 (%)': 70.0}

## B2. BM25 (1 mark)
**BM25** scores a chunk by summing, over each query word, *how rare the word is* (IDF) × *how often it appears in the chunk*
(TF), with two corrections:
* **TF saturation (`k1 = 1.5`)** — the 10th "maintenance" in a chunk adds far less than the 1st.
* **Length normalisation (`b = 0.75`)** — long chunks are penalised for containing more words by chance.

Tokenisation: lowercase, split on non-alphanumerics (so `ISO 9001` → `iso`, `9001`), and drop common English stopwords,
which carry no topical signal. Note that OCR damage hurts BM25 directly: `management-ied` becomes `management` + `ied`,
and `led` will never match it.

In [30]:
from rank_bm25 import BM25Okapi

STOPWORDS = set("""a an and are as at be been being but by can could did do does for from had has have how i if in into is
it its may might must not of on or our should so such than that the their them then there these they this those to was
we were what when where which while who why will with would you your""".split())

def bm25_tokenize(text: str):
    return [t for t in re.findall(r"[a-z0-9]+", text.lower()) if t not in STOPWORDS]

class BM25Index:
    def __init__(self, chunks, k1=1.5, b=0.75):
        self.chunks = chunks
        t0 = time.perf_counter()
        self.bm25 = BM25Okapi([bm25_tokenize(c["text"]) for c in chunks], k1=k1, b=b)
        self.build_seconds = time.perf_counter() - t0

    def search(self, query: str, k: int = TOP_K):
        scores = self.bm25.get_scores(bm25_tokenize(query))
        top = np.argsort(-scores)[:k]
        return [{**self.chunks[i], "score": float(scores[i]), "rank": r} for r, i in enumerate(top, start=1)]

bm25 = BM25Index(CHUNKS)
print(f"BM25 index built over {len(CHUNKS):,} chunks in {bm25.build_seconds:.2f} s")
print("Query tokens for Q8:", bm25_tokenize(EVAL[7]["query"]))

def bm25_search(query, k=TOP_K):
    return bm25.search(query, k)

b_summary["BM25"], b_per_query["BM25"] = evaluate(bm25_search)
b_summary["BM25"]

BM25 index built over 1,601 chunks in 0.27 s
Query tokens for Q8: ['common', 'elements', 'included', 'iso', '9001', 'iso', '9002', 'iso', '9003', 'quality', 'system', 'models']

{'Average query latency (ms)': 3.09,
 'Hit rate@1 (%)': 10.0,
 'Hit rate@3 (%)': 30.0,
 'Hit rate@5 (%)': 50.0}

## B3. Hybrid with Reciprocal Rank Fusion (1 mark)
Dense scores (cosine, ~0.5–0.9) and BM25 scores (unbounded, ~5–40) are on different scales, so adding them is meaningless.
**RRF uses only ranks:**

$$\text{RRF}(d) = \frac{1}{60 + \text{rank}_\text{dense}(d)} + \frac{1}{60 + \text{rank}_\text{BM25}(d)}$$

We fuse the **top 20** of each list (a chunk missing from a list gets 0 from it) and keep the top 5. The constant 60
flattens the curve: rank 1 is worth 1/61 ≈ 0.0164 and rank 20 still 1/80 = 0.0125, so a chunk ranked fairly well by
*both* methods (e.g. 4th and 6th → 0.0156 + 0.0152 = 0.0308) beats a chunk ranked 1st by only one (0.0164).

In [31]:
RRF_K, FUSE_DEPTH = 60, 20

def rrf_fuse(ranked_lists: dict, k=TOP_K, rrf_k=RRF_K):
    # ranked_lists: {"dense": [...], "bm25": [...]}, each a list of results with 1-based "rank"
    fused = {}
    for method, results in ranked_lists.items():
        for r in results:
            entry = fused.setdefault(r["chunk_id"], {**r, "score": 0.0, "dense_rank": None, "bm25_rank": None})
            entry["score"] += 1.0 / (rrf_k + r["rank"])
            entry[f"{method}_rank"] = r["rank"]
    best = sorted(fused.values(), key=lambda x: x["score"], reverse=True)[:k]
    return [{**r, "rank": i} for i, r in enumerate(best, start=1)]

def hybrid_search(query, k=TOP_K):
    return rrf_fuse({"dense": dense.search(query, FUSE_DEPTH), "bm25": bm25.search(query, FUSE_DEPTH)}, k)

b_summary["Hybrid (RRF)"], b_per_query["Hybrid (RRF)"] = evaluate(hybrid_search)

# Worked example: where did the fused top 5 come from?
e = EVAL[2]   # Q3: dense rank 2, BM25 rank 5 -> fused rank 1
print(f"Q{e['qid']}: {e['query']}\n")
pd.DataFrame([{"fused rank": r["rank"], "RRF score": round(r["score"], 4), "dense rank": r["dense_rank"],
               "BM25 rank": r["bm25_rank"], "doc": r["doc"], "contains span": is_hit(r["text"], e["span"])}
              for r in hybrid_search(e["query"])])

Q3: What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the report?

,fused rank,RRF score,dense rank,BM25 rank,doc,contains span
0,1,0.0315,2,5,NIST_Malcolm_Baldrige_Quality.txt,True
1,2,0.0296,1,16,NIST_Malcolm_Baldrige_Quality.txt,False
2,3,0.0295,4,12,NIST_ISO9000_Quality_Systems.txt,False
3,4,0.0271,11,17,NIST_Manufacturing_Handbook.txt,False
4,5,0.0263,17,15,NIST_Manufacturing_Machinery_Maintenance.txt,False

### Search comparison table

In [32]:
b_table = pd.DataFrame(b_summary).T.rename_axis("Method").reset_index()
b_table

,Method,Average query latency (ms),Hit rate@1 (%),Hit rate@3 (%),Hit rate@5 (%)
0,Dense,11.86,0.0,60.0,70.0
1,BM25,3.09,10.0,30.0,50.0
2,Hybrid (RRF),14.16,20.0,60.0,70.0

In [33]:
# Per query: rank (1-5) of the first chunk containing the answer span, "-" = not in top 5
pd.DataFrame({m: [p["hit_rank"] or "-" for p in rows] for m, rows in b_per_query.items()},
             index=[f"Q{e['qid']}: {e['query'][:60]}" for e in EVAL])

,Dense,BM25,Hybrid (RRF)
Q1: How did Malcolm Baldrige quality concepts influence the STEP,5,2,3
Q2: How can workstation design reduce excessive reaching and awk,3,-,4
Q3: What three kinds of evidence can be used to assess results u,2,5,1
Q4: Why are statistical methods useful when analysing manufactur,-,-,-
Q5: What is the difference between reactive maintenance and more,-,-,-
Q6: What costs are included when analysing direct and indirect m,2,-,2
Q7: What is the difference between Type A and Type B evaluations,3,5,3
"Q8: What common elements are included in the ISO 9001, ISO 9002,",2,2,2
Q9: Why is management involvement important in a quality-improve,3,1,1
Q10: What is the main purpose of machine guarding?,-,-,-

**Observations from the Part B results**
* **Hybrid gives the best rank 1:** hit@1 is 20% (Q3, Q9), vs 0% for dense and 10% for BM25, with the same hit@3 (60%) and hit@5 (70%) as dense.
* **The two methods fail on different queries**, which is what RRF needs. BM25 wins where the query shares rare exact words with
  the passage (Q1 "Malcolm Baldrige … STEP" rank 2 vs dense 5; Q9 "management … quality improvement" rank 1 vs dense 3). Dense wins on
  paraphrases (Q2 "reaching / posture" vs the text's "diverters … reduces reaches", Q6 "costs" — BM25 misses both).
* **Agreement beats a single first place.** Q3 is ranked 2nd by dense and 5th by BM25; neither puts it first, but it is the only chunk
  both rank highly, so RRF puts it at rank 1 (1/62 + 1/65 = 0.0315).
* **Fusion can also cost a little:** Q2 drops from dense rank 3 to hybrid rank 4, because BM25 contributes nothing for it while other
  chunks collect points from both lists.
* **BM25 is weakest overall (30% hit@3)** — the corpus is OCR text and the questions are paraphrased, so exact word overlap is low.
* **Q4, Q5, Q10 are missed by all three methods in the top 5.** For Q5, every top result comes from the correct maintenance report but
  from summary sections that mention reactive maintenance many times, not from the definition passage.
* **Latency:** BM25 is fastest (3 ms, no neural network). Dense takes ~11 ms, dominated by embedding the query on the GPU;
  hybrid (~14 ms) is roughly dense + BM25, since fusing two short lists costs almost nothing. Millisecond timings on a shared
  Colab GPU vary between runs, but all three are negligible next to LLM generation (seconds).

In [34]:
def show_top3(qid, methods=("Dense", "BM25", "Hybrid (RRF)"), width=220):
    # Side-by-side look at one query: the top-3 chunks of each method, marked HIT if they contain the span.
    e = EVAL[qid - 1]
    print(f"Q{qid}: {e['query']}\nSpan: {e['span']}\n")
    for m in methods:
        print(f"── {m} " + "─" * 60)
        for r in b_per_query[m][qid - 1]["results"][:3]:
            flag = "HIT " if is_hit(r["text"], e["span"]) else "    "
            print(f" {flag}#{r['rank']} [{r['doc']}] {r['text'][:width]}...")
        print()

show_top3(3)

Q3: What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the report?
Span: based upon one or more of three factors: (1) improvement trends; (2) current levels; and (3) benchmarks

── Dense ────────────────────────────────────────────────────────────
     #1 [NIST_Malcolm_Baldrige_Quality.txt] ) revision of plans, taking into consideration progress, learning, and new information. Figure 2. Baldrige Award Criteria Framework BALORIGE AWARD CRITERIA FRAMEWORK Dynamic Relationships 5 These specific characteristics...
 HIT #2 [NIST_Malcolm_Baldrige_Quality.txt] the Malcolm Baldrige National Quality Award. Several key characteristics directly influenced the development of the model qualification methods. A more detailed description can be found in the 1992 edition of the Award C...
     #3 [NIST_Manufacturing_Handbook.txt] ; and (iii) an outline of the method of analysis of the results. In outlining the methods of conducting and analyzing an experiment, Anderson and Ban¬ croft f give the following advice: (i) The experimenter should clearl...

── BM25 ────────────────────────────────────────────────────────────
     #1 [NIST_Malcolm_Baldrige_Quality.txt] this paper useful. An overview of a methodology for evaluating the technical quality of information and data models is also Included. These models provide the basis for the emerging STEP standard. The types of models den...
     #2 [NIST_Measurement_Uncertainty.txt] coverage factor k used to obtain it, or report u . c When reporting a measurement result and its uncertainty, include the following information in the report itself or by referring to a published document: – A list of al...
     #3 [NIST_ISO9000_Quality_Systems.txt] telecom companies and agencies to assess the extent of unreasonableness in foreign national standards, regulations, testing and certification requirements, and accreditation procedures. Order as PB 88-153630 from NTIS. o...

── Hybrid (RRF) ────────────────────────────────────────────────────────────
 HIT #1 [NIST_Malcolm_Baldrige_Quality.txt] the Malcolm Baldrige National Quality Award. Several key characteristics directly influenced the development of the model qualification methods. A more detailed description can be found in the 1992 edition of the Award C...
     #2 [NIST_Malcolm_Baldrige_Quality.txt] ) revision of plans, taking into consideration progress, learning, and new information. Figure 2. Baldrige Award Criteria Framework BALORIGE AWARD CRITERIA FRAMEWORK Dynamic Relationships 5 These specific characteristics...
     #3 [NIST_ISO9000_Quality_Systems.txt] the relevant ISO decision making body. HOW DO THE ISO 9000 CRITERIA COMPARE WITH CRITERIA USED IN THE MALCOLM BALDRIGE NATIONAL QUALITY AWARD PROCESS? The Malcolm Baldrige National Quality Award process is designed to re...


## B4. Which method works best, and why (1 mark)
**Hybrid (RRF) works best for our queries:** it has the highest hit@1 (20% vs 0% dense, 10% BM25), the same hit@3 as dense (60%),
for only ~3 ms more than dense (14 vs 11 ms; both are dominated by embedding the query). Dense and BM25 make different mistakes — dense matches meaning but ranks long, mixed-topic chunks
loosely, while BM25 rewards exact technical terms but misses paraphrases — so fusing their ranks promotes chunks that both consider
relevant. For example, for Q3 ("What three kinds of evidence can be used to assess results…") dense ranked the answer chunk 2nd and
BM25 5th, but because it was the only chunk high in *both* lists, RRF moved it to rank 1.

---
# Part C — Reranking (4 marks)

**Why rerank?** Dense search is a *bi-encoder*: the query and each chunk are embedded **separately**, and similarity is one dot
product. That is fast enough to search thousands of chunks, but the chunk vector was computed without knowing the question, so a
400-token chunk is compressed into one "average" meaning. A **cross-encoder** reads the query and the chunk **together** in one
transformer pass, so every query word can attend to every chunk word, and outputs a single relevance score. It is much more accurate but
needs one forward pass per (query, chunk) pair, so it is only used on a short candidate list:

```
1,601 chunks ──hybrid (fast, recall)──► top 10 ──cross-encoder (slow, precision)──► top 3 ──► LLM
```

**Model:** `cross-encoder/ms-marco-MiniLM-L-6-v2` (6-layer MiniLM, trained on MS MARCO question → passage relevance).
Its input limit is 512 tokens; a query (~25 tokens) + a 400-token chunk + 3 special tokens fits, so nothing is truncated
(both models use the same uncased BERT WordPiece vocabulary).

**Important limit:** a reranker can only *reorder* the candidates it receives. If the answer chunk is not in the hybrid top 10,
no reranker can recover it, so we first measure hit@10 as the ceiling.

In [35]:
from sentence_transformers import CrossEncoder

RERANK_MODEL_ID = "cross-encoder/ms-marco-MiniLM-L-6-v2"
CANDIDATES_K, FINAL_K = 10, 3

reranker = CrossEncoder(RERANK_MODEL_ID, max_length=512, device=DEVICE)
print("Reranker:", RERANK_MODEL_ID, "| max length:", getattr(reranker, "max_seq_length", 512), "| device:", DEVICE)

# Ceiling check: in how many queries is the answer chunk among the 10 hybrid candidates?
candidates = {e["qid"]: hybrid_search(e["query"], CANDIDATES_K) for e in EVAL}
hit10 = [first_hit_rank(candidates[e["qid"]], e["span"]) for e in EVAL]
print(f"Hybrid hit@10 (best any reranker could reach for hit@1/hit@3): {100 * np.mean([r is not None for r in hit10]):.0f}%")
print("Rank of answer chunk in the hybrid top 10:", {f"Q{e['qid']}": r or "-" for e, r in zip(EVAL, hit10)})

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Reranker: cross-encoder/ms-marco-MiniLM-L-6-v2 | max length: 512 | device: cuda
Hybrid hit@10 (best any reranker could reach for hit@1/hit@3): 80%
Rank of answer chunk in the hybrid top 10: {'Q1': 3, 'Q2': 4, 'Q3': 1, 'Q4': '-', 'Q5': 7, 'Q6': 2, 'Q7': 3, 'Q8': 2, 'Q9': 1, 'Q10': '-'}

## C1. Rerank the hybrid top 10 and keep the top 3 (1 mark)
`rerank()` scores every (query, chunk) pair with the cross-encoder, sorts by that score and keeps the top 3. Only the
cross-encoder step is timed (one warm-up call first), since the retrieval cost was already measured in Part B.

In [36]:
def rerank(query, cands, top_n=FINAL_K):
    scores = reranker.predict([(query, c["text"]) for c in cands], batch_size=16, show_progress_bar=False)
    order = np.argsort(-scores)
    return [{**cands[i], "hybrid_rank": cands[i]["rank"], "ce_score": float(scores[i]), "rank": new_rank}
            for new_rank, i in enumerate(order[:top_n], start=1)]

rerank(EVAL[0]["query"], candidates[1])                       # warm-up, not timed

reranked, rerank_ms = {}, []
for e in EVAL:
    t0 = time.perf_counter()
    reranked[e["qid"]] = rerank(e["query"], candidates[e["qid"]])
    rerank_ms.append((time.perf_counter() - t0) * 1000)

print(f"Reranked {len(EVAL)} queries | {CANDIDATES_K} candidates each | avg {np.mean(rerank_ms):.1f} ms per query")

Reranked 10 queries | 10 candidates each | avg 57.4 ms per query

## C2. Top 3 before and after reranking (1 mark)
Each cell lists the top-3 chunk ids; ✅ marks the chunk that contains the answer span. `hybrid rank` shows where each reranked chunk
sat in the hybrid list. **Rank change rate** = share of the 10 queries whose first result changes after reranking.

In [37]:
def fmt(results, span):
    return "  ".join(f"#{r['chunk_id']}{'✅' if is_hit(r['text'], span) else ''}" for r in results)

c2_rows = []
for e in EVAL:
    before, after = candidates[e["qid"]][:FINAL_K], reranked[e["qid"]]
    c2_rows.append({
        "qid": e["qid"],
        "top 3 before (hybrid)": fmt(before, e["span"]),
        "top 3 after (rerank)": fmt(after, e["span"]),
        "hybrid ranks of new top 3": [r["hybrid_rank"] for r in after],
        "first result changed": before[0]["chunk_id"] != after[0]["chunk_id"],
        "hit rank before": first_hit_rank(before, e["span"]) or "-",
        "hit rank after": first_hit_rank(after, e["span"]) or "-",
    })
c2_table = pd.DataFrame(c2_rows)
rank_change_rate = 100 * c2_table["first result changed"].mean()
print(f"Rank change rate: {rank_change_rate:.0f}%")
c2_table

Rank change rate: 40%

,qid,top 3 before (hybrid),top 3 after (rerank),hybrid ranks of new top 3,first result changed,hit rank before,hit rank after
0,1,#33 #31 #29✅,#32 #31 #29✅,"[6, 2, 3]",True,3,3
1,2,#1172 #1173 #1171,#1172 #1174✅ #1173,"[1, 4, 2]",False,-,2
2,3,#32✅ #33 #11,#32✅ #33 #29,"[1, 2, 6]",False,1,1
3,4,#1052 #405 #78,#1052 #405 #78,"[1, 2, 3]",False,-,-
4,5,#921 #968 #969,#921 #968 #914,"[1, 2, 6]",False,-,-
5,6,#944 #932✅ #928,#932✅ #944 #967,"[2, 1, 6]",True,2,1
6,7,#1018 #983 #982✅,#983 #986 #1018,"[2, 4, 1]",True,3,-
7,8,#8 #7✅ #6,#8 #7✅ #9,"[1, 2, 4]",False,2,2
8,9,#28✅ #43 #1248,#34 #43 #28✅,"[9, 2, 1]",True,1,3
9,10,#1475 #1481 #1483,#1475 #1479 #1481,"[1, 10, 2]",False,-,-

In [38]:
def show_rerank(qid, width=200):
    # Readable before/after view of one query's top 3, with the start of each chunk's text.
    e = EVAL[qid - 1]
    print(f"Q{qid}: {e['query']}\nSpan: {e['span']}\n")
    for label, results in [("BEFORE (hybrid)", candidates[qid][:FINAL_K]), ("AFTER (cross-encoder)", reranked[qid])]:
        print(f"── {label} " + "─" * 50)
        for r in results:
            flag = "HIT " if is_hit(r["text"], e["span"]) else "    "
            extra = f" (was hybrid #{r['hybrid_rank']}, score {r['ce_score']:.2f})" if "ce_score" in r else ""
            print(f" {flag}#{r['rank']}{extra} [{r['doc']}] {r['text'][:width]}...")
        print()

for e in EVAL:
    show_rerank(e["qid"])

Q1: How did Malcolm Baldrige quality concepts influence the STEP model qualification approach?
Span: Many basic concepts of the Malcolm Baldrige National Quality Award were used in building the foundation for this new approach to standards development

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [NIST_Malcolm_Baldrige_Quality.txt] ) revision of plans, taking into consideration progress, learning, and new information. Figure 2. Baldrige Award Criteria Framework BALORIGE AWARD CRITERIA FRAMEWORK Dynamic Relationships 5 These spec...
     #2 [NIST_Malcolm_Baldrige_Quality.txt] information modeling in a much larger context. The ultimate objective is a common understanding of semantics and a standard syntax for information specification. These features are two of the benefits...
 HIT #3 [NIST_Malcolm_Baldrige_Quality.txt] this paper useful. An overview of a methodology for evaluating the technical quality of information and data models is also Included. These models provide the basis for the emerging STEP standard. The...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #6, score 5.74) [NIST_Malcolm_Baldrige_Quality.txt] the Malcolm Baldrige National Quality Award. Several key characteristics directly influenced the development of the model qualification methods. A more detailed description can be found in the 1992 ed...
     #2 (was hybrid #2, score 5.65) [NIST_Malcolm_Baldrige_Quality.txt] information modeling in a much larger context. The ultimate objective is a common understanding of semantics and a standard syntax for information specification. These features are two of the benefits...
 HIT #3 (was hybrid #3, score 3.84) [NIST_Malcolm_Baldrige_Quality.txt] this paper useful. An overview of a methodology for evaluating the technical quality of information and data models is also Included. These models provide the basis for the emerging STEP standard. The...

Q2: How can workstation design reduce excessive reaching and awkward upper-body posture?
Span: This conveyor has diverters in place that push the products closer to the workers. This reduces reaches for the employees.

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [OSHA_Ergonomics_Workplace.txt] falls within the “OK” zones in the pictures above. The postures to avoid are ones that force you to raise the upper arms or ones that require the arm to be extended behind the body. Slide 34 Risk Fact...
     #2 [OSHA_Ergonomics_Workplace.txt] the wrist. Discussion: Notice that the left hand holds and supports the product. You would expect reports of discomfort to the left hand from employees. Also note the head tilt angle. Slide 39 Risk Fa...
     #3 [OSHA_Ergonomics_Workplace.txt] process totes. This allows the worker to place the tote at a comfortable height and then dump it onto the processing line using the mechanism. The dumping activity can often be a problem because the e...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #1, score 1.96) [OSHA_Ergonomics_Workplace.txt] falls within the “OK” zones in the pictures above. The postures to avoid are ones that force you to raise the upper arms or ones that require the arm to be extended behind the body. Slide 34 Risk Fact...
 HIT #2 (was hybrid #4, score -0.85) [OSHA_Ergonomics_Workplace.txt] Risk Factors - Awkward Postures The worker here is wrapping the pallets with a plastic film. He is already leaning to one side slightly. As he gets lower on the pallet, the sideways leaning will get m...
     #3 (was hybrid #2, score -1.87) [OSHA_Ergonomics_Workplace.txt] the wrist. Discussion: Notice that the left hand holds and supports the product. You would expect reports of discomfort to the left hand from employees. Also note the head tilt angle. Slide 39 Risk Fa...

Q3: What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the report?
Span: based upon one or more of three factors: (1) improvement trends; (2) current levels; and (3) benchmarks

── BEFORE (hybrid) ──────────────────────────────────────────────────
 HIT #1 [NIST_Malcolm_Baldrige_Quality.txt] the Malcolm Baldrige National Quality Award. Several key characteristics directly influenced the development of the model qualification methods. A more detailed description can be found in the 1992 ed...
     #2 [NIST_Malcolm_Baldrige_Quality.txt] ) revision of plans, taking into consideration progress, learning, and new information. Figure 2. Baldrige Award Criteria Framework BALORIGE AWARD CRITERIA FRAMEWORK Dynamic Relationships 5 These spec...
     #3 [NIST_ISO9000_Quality_Systems.txt] the relevant ISO decision making body. HOW DO THE ISO 9000 CRITERIA COMPARE WITH CRITERIA USED IN THE MALCOLM BALDRIGE NATIONAL QUALITY AWARD PROCESS? The Malcolm Baldrige National Quality Award proce...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
 HIT #1 (was hybrid #1, score 0.65) [NIST_Malcolm_Baldrige_Quality.txt] the Malcolm Baldrige National Quality Award. Several key characteristics directly influenced the development of the model qualification methods. A more detailed description can be found in the 1992 ed...
     #2 (was hybrid #2, score -0.89) [NIST_Malcolm_Baldrige_Quality.txt] ) revision of plans, taking into consideration progress, learning, and new information. Figure 2. Baldrige Award Criteria Framework BALORIGE AWARD CRITERIA FRAMEWORK Dynamic Relationships 5 These spec...
     #3 (was hybrid #6, score -2.07) [NIST_Malcolm_Baldrige_Quality.txt] this paper useful. An overview of a methodology for evaluating the technical quality of information and data models is also Included. These models provide the basis for the emerging STEP standard. The...

Q4: Why are statistical methods useful when analysing manufacturing experiments?
Span: One of the most frequent uses of statistics is in testing for differences.

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [NIST_QIF_Quality_Information_Framework.txt] by Walter A. Shewhart at Bell Laboratories in the early 1920s [27]. SPC aims to detect quality (and by implication process) variation at any point of 17 time. In the context of the quality life cycle,...
     #2 [NIST_Manufacturing_Handbook.txt] Massey, Jr., Intro¬ duction to Statistical Analysis (2d ed.), Chapter 19, “Sensitivity Experiments,” McGraw-Hill Book Co., Inc., New York, N.Y., 1957. 9. W. J. Dixon and A. M. Mood, “A Method for Obta...
     #3 [NIST_Manufacturing_Handbook.txt] usefulness of particu¬ lar statistical techniques, is urged to carry out a few “dry runs” with such simulated measurements of known characteristics. All A-Tables referenced in these Chapters are conta...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #1, score 1.35) [NIST_QIF_Quality_Information_Framework.txt] by Walter A. Shewhart at Bell Laboratories in the early 1920s [27]. SPC aims to detect quality (and by implication process) variation at any point of 17 time. In the context of the quality life cycle,...
     #2 (was hybrid #2, score 1.10) [NIST_Manufacturing_Handbook.txt] Massey, Jr., Intro¬ duction to Statistical Analysis (2d ed.), Chapter 19, “Sensitivity Experiments,” McGraw-Hill Book Co., Inc., New York, N.Y., 1957. 9. W. J. Dixon and A. M. Mood, “A Method for Obta...
     #3 (was hybrid #3, score 1.10) [NIST_Manufacturing_Handbook.txt] usefulness of particu¬ lar statistical techniques, is urged to carry out a few “dry runs” with such simulated measurements of known characteristics. All A-Tables referenced in these Chapters are conta...

Q5: What is the difference between reactive maintenance and more advanced maintenance strategies?
Span: is maintenance done, typically, after equipment has failed to produce a product within desired quality or production targets

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [NIST_Manufacturing_Machinery_Maintenance.txt] Survey in Section 3. Direct maintenance costs are discussed in Section 4. Section 5 discusses losses, including downtime, lost sales, and defects along with additional losses and injuries due to inade...
     #2 [NIST_Manufacturing_Machinery_Maintenance.txt] Advanced Maintenance Techniques The perceived benefit of potentially adopting some amount of predictive maintenance was $6.5 billion from downtime reduction and $67.3 billion in increased sales. Other...
     #3 [NIST_Manufacturing_Machinery_Maintenance.txt] , 35 % fewer lost sales due to defects from maintenance, and 29 % less lost sales due to delays from maintenance issues. Those who invest more heavily in maintenance were more likely to have a pull (i...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #1, score 4.88) [NIST_Manufacturing_Machinery_Maintenance.txt] Survey in Section 3. Direct maintenance costs are discussed in Section 4. Section 5 discusses losses, including downtime, lost sales, and defects along with additional losses and injuries due to inade...
     #2 (was hybrid #2, score 4.59) [NIST_Manufacturing_Machinery_Maintenance.txt] Advanced Maintenance Techniques The perceived benefit of potentially adopting some amount of predictive maintenance was $6.5 billion from downtime reduction and $67.3 billion in increased sales. Other...
     #3 (was hybrid #6, score 4.53) [NIST_Manufacturing_Machinery_Maintenance.txt] on reactive maintenance, and more on preventive and/or predictive maintenance, were more likely to use a pull (i.e., make to order) stock strategy and tend to be differentiators as opposed to being a ...

Q6: What costs are included when analysing direct and indirect machinery-maintenance impacts?
Span: Direct maintenance and repair costs include the cost of labor and materials along with cascading effects

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [NIST_Manufacturing_Machinery_Maintenance.txt] . Additional Costs due to Faults and Failure In addition to direct maintenance costs (e.g., maintenance department costs), there are potentially unscheduled costs such as damage that might be caused b...
 HIT #2 [NIST_Manufacturing_Machinery_Maintenance.txt] 1 TOTAL 7 21 13 13 4 9 4 71 16 This publication is available free of charge from: https://doi.org/10.6028/NIST.AMS.100-34 Maintenance Costs and Associated Inventory Costs Direct maintenance and repair...
     #3 [NIST_Manufacturing_Machinery_Maintenance.txt] This publication is available free of charge from: https://doi.org/10.6028/NIST.AMS.100-34 Survey and Sampling Data was collected from manufacturing establishments through a survey instrument, the Mac...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
 HIT #1 (was hybrid #2, score 2.09) [NIST_Manufacturing_Machinery_Maintenance.txt] 1 TOTAL 7 21 13 13 4 9 4 71 16 This publication is available free of charge from: https://doi.org/10.6028/NIST.AMS.100-34 Maintenance Costs and Associated Inventory Costs Direct maintenance and repair...
     #2 (was hybrid #1, score 2.08) [NIST_Manufacturing_Machinery_Maintenance.txt] . Additional Costs due to Faults and Failure In addition to direct maintenance costs (e.g., maintenance department costs), there are potentially unscheduled costs such as damage that might be caused b...
     #3 (was hybrid #6, score 1.16) [NIST_Manufacturing_Machinery_Maintenance.txt] of this type will vary depending on how costs are categorized. Categorizing costs by NAICS code and measuring them in terms of value added using NIST’s Manufacturing Cost Guide, both costs and losses ...

Q7: What is the difference between Type A and Type B evaluations of uncertainty?
Span: The evaluation of uncertainty by the statistical analysis of series of observations is termed a Type A evaluation

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [NIST_Measurement_Uncertainty.txt] table also shows how one can indicate whether a component arose from a random effect in the current measurement process or from a systematic effect in the current measurement process, assuming that su...
     #2 [NIST_Measurement_Uncertainty.txt] ) are characterized by estimated covariances [see Appendix A, Eq. (A-3)] or estimated correlation coefficients. 3. Type A Evaluation of Standard Uncertainty A Type A evaluation of standard uncertainty...
 HIT #3 [NIST_Measurement_Uncertainty.txt] A while in other cases by method B (see subsection 2.2), as may be an uncertainty component arising from a random effect. NOTE – The difference between error and uncertainty should always be borne in ...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #2, score 6.39) [NIST_Measurement_Uncertainty.txt] ) are characterized by estimated covariances [see Appendix A, Eq. (A-3)] or estimated correlation coefficients. 3. Type A Evaluation of Standard Uncertainty A Type A evaluation of standard uncertainty...
     #2 (was hybrid #4, score 5.97) [NIST_Measurement_Uncertainty.txt] soundly based Type B evaluations. 5. Combined Standard Uncertainty 5.1 The combined standard uncertainty of a measure­ ment result, suggested symbol u , is taken to represent the c estimated standard ...
     #3 (was hybrid #1, score 5.16) [NIST_Measurement_Uncertainty.txt] table also shows how one can indicate whether a component arose from a random effect in the current measurement process or from a systematic effect in the current measurement process, assuming that su...

Q8: What common elements are included in the ISO 9001, ISO 9002, and ISO 9003 quality-system models?
Span: Common elements in ISO 9001, 9002, and 9003 include the need for; an effective quality system

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [NIST_ISO9000_Quality_Systems.txt] key terms; and provides guidance on selecting, using, and (if necessary) tailoring ISO 9001, 9002, and 9003 ISO 9001 (ANSI/ASQC Q 91) , Quality Systems - Model for Quality Assurance in Desiqn/Developm...
 HIT #2 [NIST_ISO9000_Quality_Systems.txt] their equivalent) has been or will be mandated by a U.S., foreign national, or regional government body. Conformance to ISO 9000 standards is also being required in purchasing specifications with incr...
     #3 [NIST_ISO9000_Quality_Systems.txt] the ISO definitions. ISO Standard 9000-1987 defines quality system as: "the organization, structure, responsibilities, procedures, processes and resources for implementing quality management." The sta...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #1, score 7.12) [NIST_ISO9000_Quality_Systems.txt] key terms; and provides guidance on selecting, using, and (if necessary) tailoring ISO 9001, 9002, and 9003 ISO 9001 (ANSI/ASQC Q 91) , Quality Systems - Model for Quality Assurance in Desiqn/Developm...
 HIT #2 (was hybrid #2, score 4.88) [NIST_ISO9000_Quality_Systems.txt] their equivalent) has been or will be mandated by a U.S., foreign national, or regional government body. Conformance to ISO 9000 standards is also being required in purchasing specifications with incr...
     #3 (was hybrid #4, score 4.18) [NIST_ISO9000_Quality_Systems.txt] once every five years. ISO has already begun to revise and supplement the ISO 9000 series. Some of these standards/guidelines will supplement ISO 9000 and ISO 9004, while others will be included in th...

Q9: Why is management involvement important in a quality-improvement program?
Span: quality improvement programs must be management-ied and customer-oriented

── BEFORE (hybrid) ──────────────────────────────────────────────────
 HIT #1 [NIST_Malcolm_Baldrige_Quality.txt] NISTIR 4738 Models, Managing Models, Quality Models: An Example of Quality Management Joan E. Tyler DEPARTMENT OF COMMERCE Natlosal InstMute of Standards and Tsdinology Manufacturing Enginsaring labor...
     #2 [NIST_Malcolm_Baldrige_Quality.txt] Qualification Methods team to provide the continuous feedback necessary for quality improvement. There have been regular cycles of enhanced model qualification methods from the methods team, followed ...
     #3 [OSHA_General_Industry_Standards.txt] of the role of student evaluations to provide feedback for training program improvement. D. Quality control and evaluation. Adequacy and appropriateness of quality control and evaluation plans for tra...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #9, score -0.74) [NIST_Malcolm_Baldrige_Quality.txt] ed foundations." This is an important concern for companies which build products to the standard or the companies which buy products built to the standard. To mitigate this problem, the quality strate...
     #2 (was hybrid #2, score -1.44) [NIST_Malcolm_Baldrige_Quality.txt] Qualification Methods team to provide the continuous feedback necessary for quality improvement. There have been regular cycles of enhanced model qualification methods from the methods team, followed ...
 HIT #3 (was hybrid #1, score -1.89) [NIST_Malcolm_Baldrige_Quality.txt] NISTIR 4738 Models, Managing Models, Quality Models: An Example of Quality Management Joan E. Tyler DEPARTMENT OF COMMERCE Natlosal InstMute of Standards and Tsdinology Manufacturing Enginsaring labor...

Q10: What is the main purpose of machine guarding?
Span: Safeguarding is essential for protecting employees from needless and preventable injury.

── BEFORE (hybrid) ──────────────────────────────────────────────────
     #1 [OSHA_Machine_Guarding_Standards.txt] safeguarded. In this booklet, the term primary safeguarding methods refers to machine guarding techniques that are intended to prevent or greatly reduce the chance that an employee will have an amputa...
     #2 [OSHA_Machine_Guarding_Standards.txt] ’s move- ment and may obstruct their work space. • Operator may easily make device ineffective by not adjusting the device properly. Table 2. Types of Safeguarding Devices Types of Machine Guards 1 4 ...
     #3 [OSHA_Machine_Guarding_Standards.txt] anti- tiedown ineffective. • Protects the operator only. • Operator may make devices without anti- tiedown ineffective. • Protects the operator only. • Sometimes impractical because distance require- ...

── AFTER (cross-encoder) ──────────────────────────────────────────────────
     #1 (was hybrid #1, score 3.82) [OSHA_Machine_Guarding_Standards.txt] safeguarded. In this booklet, the term primary safeguarding methods refers to machine guarding techniques that are intended to prevent or greatly reduce the chance that an employee will have an amputa...
     #2 (was hybrid #10, score 1.36) [OSHA_Machine_Guarding_Standards.txt] Adjusting Interlocking Barrier Guards Method of Safeguarding Barrier that allows for stock feeding but does not permit operator to reach the danger area. Barrier that adjusts for a variety of producti...
     #3 (was hybrid #2, score 0.74) [OSHA_Machine_Guarding_Standards.txt] ’s move- ment and may obstruct their work space. • Operator may easily make device ineffective by not adjusting the device properly. Table 2. Types of Safeguarding Devices Types of Machine Guards 1 4 ...

## C3. Reranking measurements (1 mark)

In [39]:
hit1_before = b_summary["Hybrid (RRF)"]["Hit rate@1 (%)"]
hit3_before = b_summary["Hybrid (RRF)"]["Hit rate@3 (%)"]
ranks_after = [first_hit_rank(reranked[e["qid"]], e["span"]) for e in EVAL]
hit1_after  = 100 * np.mean([r == 1 for r in ranks_after])
hit3_after  = 100 * np.mean([r is not None for r in ranks_after])

c3_table = pd.DataFrame([
    ("Reranking time per query (ms)", f"{np.mean(rerank_ms):.1f}"),
    ("Rank change rate (%)", f"{rank_change_rate:.0f}"),
    ("Hit rate@1 before reranking (from Part B, Hybrid RRF) (%)", f"{hit1_before:.0f}"),
    ("Hit rate@1 after reranking (%)", f"{hit1_after:.0f}"),
    ("Hit rate@3 before → after (%) [extra]", f"{hit3_before:.0f} → {hit3_after:.0f}"),
    ("Hybrid hit@10 = reranking ceiling (%) [extra]", f"{100 * np.mean([r is not None for r in hit10]):.0f}"),
], columns=["Measure", "Value"])
c3_table

                                                     Measure    Value
0                              Reranking time per query (ms)     57.4
1                                       Rank change rate (%)       40
2  Hit rate@1 before reranking (from Part B, Hybrid RRF) (%)       20
3                             Hit rate@1 after reranking (%)       20
4                      Hit rate@3 before → after (%) [extra]  60 → 60
5              Hybrid hit@10 = reranking ceiling (%) [extra]       80

**Observations from the reranking results**

| Query | Answer-span rank, hybrid → reranked | What happened |
|---|---|---|
| Q6 | 2 → **1** | gain: the cost-definition chunk moved to the top |
| Q2 | 4 → **2** | gain: pulled up from outside the top 3 |
| Q9 | 1 → 3 | loss on the metric, but the new #2 (chunk 43, *"Management Role … management by fact"*) is the passage the expected answer paraphrases |
| Q7 | 3 → out | loss: chunk 982 (both Type A/B definitions) replaced by 983 (Type A section) and 986 (combining A and B) |
| Q1 | 3 → 3 | top-1 changed to chunk 32 (*"Several key characteristics directly influenced the development of the model qualification methods"*) — the passage the expected answer is written from |
| Q4, Q10 | not in top 10 | the **ceiling**: no reranker can recover an answer that retrieval never returned |

**A limit of single-span evaluation.** Each query has one marked answer span, but some answers are spread over several passages.
For Q1 and Q9 the cross-encoder promoted chunks that genuinely answer the question yet do not contain *our* marked sentence, so hit@1
under-credits it. The spans were marked before the experiments and are kept fixed so that all methods are scored the same way; in
Part D the LLM judge compares answers with the expected answer directly, which does not depend on spans.


## C4. Did reranking help? (1 mark)
**By the hit-rate metric, reranking did not help in our domain:** hit@1 stayed at 20% and hit@3 at 60%, while each query paid about
52 ms extra — about 3.7× the cost of the hybrid search itself (14 ms), though still small next to the seconds an LLM needs to generate an answer.
It changed the first result for 4 of 10 queries, and gains (Q6 to rank 1, Q2 into the top 3) were cancelled by losses (Q9, Q7).
Inspection shows the metric understates it — for Q1 and Q9 the reranker promoted the passages the expected answers were written from —
so we keep it for Part D, where the quality of the 3 chunks given to the model matters more than 52 ms.

In [40]:
# Hand-off to Part D: the final top-3 chunks per query (also saved to disk as a record of the retrieval output)
FINAL_TOP3 = {e["qid"]: [{"chunk_id": r["chunk_id"], "doc": r["doc"], "text": r["text"]} for r in reranked[e["qid"]]]
              for e in EVAL}
with open("reranked_top3.json", "w", encoding="utf-8") as f:
    json.dump({"chunk_size": CHOSEN_SIZE, "eval": EVAL, "top3": FINAL_TOP3}, f, ensure_ascii=False, indent=1)
print("Saved reranked_top3.json")

Saved reranked_top3.json

---
# Part D — Generate and check answers (7 marks)

```
question ─► hybrid top 10 ─► cross-encoder top 3 ─► numbered prompt ─► GENERATOR ─► answer with [n] citations
                                                                                           │
                       question + expected answer + the same 3 chunks + answer ─► JUDGE ─► CORRECT / SUPPORTED
```

| Role | Model | Why |
|---|---|---|
| Generator | **TinyLlama-1.1B-Chat + QLoRA Adapter B** (Assignment 1), 4-bit NF4 | required by the assignment |
| Fallback generator (only if needed) | `microsoft/Phi-3.5-mini-instruct`, 4-bit | used only if the 1.1B model ignores the chunks or never says "Not found" |
| Judge | `Qwen/Qwen2.5-7B-Instruct`, 4-bit, greedy decoding (temperature 0) | stronger than the generator, different model family from both generators, not gated on Hugging Face |

**Before running:** copy the Assignment 1 adapter folder `qlora_adapter_b_final/` (from Prayogshala
`/home/jovyan/adapters/qlora_adapter_b_final`) into Google Drive at `MyDrive/qlora_adapter_b_final/`. It must contain
`adapter_config.json` and `adapter_model.safetensors`. Models are loaded one at a time and freed after use, so everything fits on a 15 GB T4.

In [41]:
%pip install -q peft bitsandbytes accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 23.8 MB/s eta 0:00:00

In [42]:
import gc
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
from peft import PeftModel

if not torch.cuda.is_available():
    # Say *why* there is no GPU before stopping: no GPU attached to the session, or a CPU-only PyTorch build
    import shutil, subprocess
    smi = subprocess.run(["nvidia-smi", "-L"], capture_output=True, text=True).stdout.strip() if shutil.which("nvidia-smi") else ""
    print("torch", torch.__version__, "| CUDA build:", torch.version.cuda,
          "| CUDA_VISIBLE_DEVICES:", os.environ.get("CUDA_VISIBLE_DEVICES"), "| nvidia-smi:", smi or "no GPU found")
    raise RuntimeError("Part D needs a GPU. Colab: Runtime > Change runtime type > T4 GPU. Prayogshala: restart the server with a GPU "
                       "profile; if nvidia-smi lists a GPU but 'CUDA build' is None, install a CUDA build of torch and restart the kernel.")

# T4 (compute capability 7.5) has no native bfloat16, so compute in float16 there
COMPUTE_DTYPE = torch.bfloat16 if torch.cuda.get_device_capability()[0] >= 8 else torch.float16
BNB_4BIT = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                              bnb_4bit_compute_dtype=COMPUTE_DTYPE, bnb_4bit_use_double_quant=True)

ADAPTER_CANDIDATES = [Path("/content/drive/MyDrive/qlora_adapter_b_final"), Path("/content/qlora_adapter_b_final"),
                      Path("/home/jovyan/adapters/qlora_adapter_b_final"), Path("qlora_adapter_b_final")]
ADAPTER_PATH = next((p for p in ADAPTER_CANDIDATES if (p / "adapter_config.json").exists()), None)
assert ADAPTER_PATH, "Adapter not found: copy qlora_adapter_b_final/ from Assignment 1 into MyDrive/"
print("Compute dtype:", COMPUTE_DTYPE, "| Adapter:", ADAPTER_PATH)

def load_4bit(model_id):
    tok = AutoTokenizer.from_pretrained(model_id)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=BNB_4BIT,
                                                 dtype=COMPUTE_DTYPE, device_map="auto")
    return model.eval(), tok

def chat_generate(model, tok, messages, max_new_tokens, **gen_kwargs):
    # Greedy decoding (do_sample=False == temperature 0): the same input always gives the same output.
    prompt = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tok(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False,
                             pad_token_id=tok.pad_token_id, **gen_kwargs)
    n_in = inputs["input_ids"].shape[1]
    return tok.decode(out[0][n_in:], skip_special_tokens=True).strip(), n_in

def free_gpu(*names):
    for n in names:
        globals().pop(n, None)
    gc.collect()
    torch.cuda.empty_cache()
    print(f"GPU memory in use: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

Compute dtype: torch.float16 | Adapter: /content/qlora_adapter_b_final

## D1. Generate grounded answers (3 marks)

### D1.1 — The generation prompt (1 mark)
The rules go in the **user** message, because Adapter B was fine-tuned on user → assistant turns with no system prompt. Each
chunk is numbered and labelled with its source document, so the model can cite `[n]`.

In [43]:
NOT_FOUND = "Not found in the documents"

RAG_INSTRUCTIONS = f"""You are a manufacturing and technical-standards assistant.
Answer the question using ONLY the information in the numbered chunks below.
Rules:
1. Use only facts stated in the chunks. Do not use outside knowledge.
2. After each sentence, cite the chunk number(s) it came from in square brackets, for example [2] or [1][3].
3. If the chunks do not contain the answer, reply exactly: {NOT_FOUND}
4. Answer in at most 5 sentences."""

def build_prompt(question, chunks):
    blocks = "\n\n".join(f"[{i}] (source: {c['doc']})\n{c['text']}" for i, c in enumerate(chunks, start=1))
    return f"{RAG_INSTRUCTIONS}\n\nChunks:\n{blocks}\n\nQuestion: {question}\nAnswer (with chunk citations):"

print(build_prompt("<question>", [{"doc": "<source file>", "text": "<chunk text>"} for _ in range(3)]))

You are a manufacturing and technical-standards assistant.
Answer the question using ONLY the information in the numbered chunks below.
Rules:
1. Use only facts stated in the chunks. Do not use outside knowledge.
2. After each sentence, cite the chunk number(s) it came from in square brackets, for example [2] or [1][3].
3. If the chunks do not contain the answer, reply exactly: Not found in the documents
4. Answer in at most 5 sentences.

Chunks:
[1] (source: <source file>)
<chunk text>

[2] (source: <source file>)
<chunk text>

[3] (source: <source file>)
<chunk text>

Question: <question>
Answer (with chunk citations):

**Fitting TinyLlama's 2,048-token window.** Part A showed the top-3 chunks average ~1,440 TinyLlama tokens but can reach ~1,830.
`fit_chunks()` measures the full prompt with the generator's own tokenizer and, only when prompt + 200 answer tokens would not fit,
cuts the *longest* chunk(s) from the end until it does. Models with long windows are never trimmed.

In [44]:
MAX_NEW_TOKENS = 200

def fit_chunks(question, chunks, tok, context_limit):
    def prompt_len(cs):
        msgs = [{"role": "user", "content": build_prompt(question, cs)}]
        return len(tok(tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True))["input_ids"])

    ids = [tok(c["text"], add_special_tokens=False)["input_ids"] for c in chunks]
    overhead  = prompt_len([{**c, "text": ""} for c in chunks])
    available = context_limit - MAX_NEW_TOKENS - overhead - 16          # 16 = safety margin for re-tokenisation
    cap = max(len(x) for x in ids)
    while sum(min(len(x), cap) for x in ids) > available:
        cap -= 8
    return [{**c, "text": tok.decode(x[:cap]) if len(x) > cap else c["text"], "trimmed": len(x) > cap}
            for c, x in zip(chunks, ids)]

### The extra "not in the corpus" query (D1.3)
The corpus never mentions IATF 16949 or PPAP (checked below). This is a deliberately tempting question: it sounds like it belongs
in the domain, and Assignment 1's training data mentioned IATF 16949, so a model that ignores the chunks may answer from memory.
It goes through the same hybrid → rerank pipeline as the other queries.

In [45]:
NF_CASE = {"qid": 11, "source": "-", "span": None, "expected": NOT_FOUND,
           "query": "What documents must a supplier submit for PPAP approval under IATF 16949?"}

for term in ["IATF", "16949", "PPAP"]:
    print(f"'{term}' occurrences in corpus: {sum(t.lower().count(term.lower()) for t in docs.values())}")

FINAL_TOP3[NF_CASE["qid"]] = [{"chunk_id": r["chunk_id"], "doc": r["doc"], "text": r["text"]}
                              for r in rerank(NF_CASE["query"], hybrid_search(NF_CASE["query"], CANDIDATES_K))]
print("Retrieved for the not-found query:", [(c["chunk_id"], c["doc"]) for c in FINAL_TOP3[11]])
GEN_CASES = EVAL + [NF_CASE]

'IATF' occurrences in corpus: 0
'16949' occurrences in corpus: 0
'PPAP' occurrences in corpus: 0
Retrieved for the not-found query: [(13, 'NIST_ISO9000_Quality_Systems.txt'), (1088, 'NIST_Quality_Assurance_Manufacturing.txt'), (12, 'NIST_ISO9000_Quality_Systems.txt')]

### D1.2 — Answers from the Assignment 1 model (1 mark)

In [46]:
def answer_all(model, tok, context_limit, **gen_kwargs):
    rows = []
    for e in GEN_CASES:
        chunks = fit_chunks(e["query"], FINAL_TOP3[e["qid"]], tok, context_limit)
        t0 = time.perf_counter()
        answer, n_in = chat_generate(model, tok, [{"role": "user", "content": build_prompt(e["query"], chunks)}],
                                     MAX_NEW_TOKENS, **gen_kwargs)
        rows.append({"qid": e["qid"], "query": e["query"], "answer": answer, "chunks": chunks,
                     "prompt tokens": n_in, "trimmed": any(c["trimmed"] for c in chunks),
                     "cites chunks": bool(re.search(r"\[\d\]", answer)),
                     "says Not found": NOT_FOUND.lower() in answer.lower(),
                     "time (s)": round(time.perf_counter() - t0, 1)})
    return rows

def print_answers(rows, title):
    print(f"=== {title} ===\n")
    for r in rows:
        tag = " [NOT-IN-CORPUS QUERY]" if r["qid"] == NF_CASE["qid"] else ""
        print(f"Q{r['qid']}{tag}: {r['query']}")
        print(textwrap.indent(textwrap.fill(r["answer"], 110), "   "), "\n")

base = AutoModelForCausalLM.from_pretrained(GEN_MODEL_ID, quantization_config=BNB_4BIT, dtype=COMPUTE_DTYPE, device_map="auto")
tl_model = PeftModel.from_pretrained(base, str(ADAPTER_PATH)).eval()
# repetition_penalty: Assignment 1 found Adapter B's greedy outputs became repetitive
tl_rows = answer_all(tl_model, gen_tokenizer, TINYLLAMA_CONTEXT, repetition_penalty=1.1)
free_gpu("tl_model", "base")

print_answers(tl_rows, "TinyLlama-1.1B + Adapter B (Assignment 1 model)")
pd.DataFrame(tl_rows)[["qid", "prompt tokens", "trimmed", "cites chunks", "says Not found", "time (s)"]]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.20GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

GPU memory in use: 0.23 GB
=== TinyLlama-1.1B + Adapter B (Assignment 1 model) ===

Q1: How did Malcolm Baldrige quality concepts influence the STEP model qualification approach?
   The Malcolm Baldrige National Quality Award emphasized the importance of continuous improvement, management by
   fact, and the use of metrics in product development. The STEP qualification approach incorporates these
   principles into its approach to ensuring the quality of information models. The Baldrige approach was used as
   a guide for the STEP model qualification approach, which aimed to ensure the quality of information models by
   using quality management techniques such as continuous improvement, management by fact, and the use of
   metrics.

Q2: How can workstation design reduce excessive reaching and awkward upper-body posture?
   The answer to the question "How can workstation design reduce excessive reaching and awkward upper-body
   posture?" is by using proper equipment and tools, such as powered dumpers, vacuum devices, and better
   conveyors to deliver products, reducing the need for reaching and increasing the use of straight wrists.
   Additionally, selecting a tool that has a curved or pistol-shaped handle, replacing this operation with an
   automatic pallet wrapper, and using multiple conveyors at different locations can also help reduce reaching
   and elevated arms. Finally, discussions about the posture of the left hand during sharpening and the use of
   circular saws should be avoided.

Q3: What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the report?
   The Baldrige-inspired approach described in the report uses three kinds of evidence to assess results: (1)
   improvement trends, (2) current levels, and (3) benchmarks, evaluations, and other comparisons that establish
   levels and trends relative to the performance of others, especially appropriately selected leaders.

Q4: Why are statistical methods useful when analysing manufacturing experiments?
   Statistical methods are useful when analyzing manufacturing experiments because they provide a means of
   detecting and correcting for any potential sources of error in the experimental design, such as insufficiently
   large samples, inadequately controlled variables, or unmeasured confounding factors. By identifying and
   addressing these issues, statistical methods can help ensure the validity and reliability of the resulting
   data and conclusions. Additionally, statistical methods can also aid in interpreting and presenting the
   results of the experiments, providing insights into the underlying mechanisms and patterns that govern the
   observed data.

Q5: What is the difference between reactive maintenance and more advanced maintenance strategies?
   The difference between reactive maintenance and more advanced maintenance strategies is that reactive
   maintenance does not involve any advanced maintenance techniques, while more advanced maintenance techniques
   involve advanced maintenance capabilities based on R&D activities or emerging, commercially available
   solutions.

Q6: What costs are included when analysing direct and indirect machinery-maintenance impacts?
   The direct and indirect machinery-maintenance impacts are analyzed in the report using the following methods:
   1. Direct Maintenance Costs: Two general methods are used to estimate direct maintenance costs (e.g.,
   maintenance department expenditures). The first utilizes survey responses to the following topics:
   "Establishment size" (Question 1), "Payroll" (Question 2), "Shipments" (Question 4), "NAICS codes" (Question
   5), "Maintenance and repair" (Question 6), and "Post stratification by industry and employment size" (Equation
   3). The responses are scaled-up using industry data on payroll or shipments.  2. Inventory Uncertainty in
   Production Time: The inventory associated with maintenance is estimated by taking the average of the responses
   and multiplying by the inventory estimate from the Annual Survey of Man

Q7: What is the difference between Type A and Type B evaluations of uncertainty?
   The difference between Type A and Type B evaluations of uncertainty is that Type A evaluations involve
   estimating the standard deviation of a measurement result, while Type B evaluations involve estimating the
   combined standard uncertainty of a measurement result, which includes individual standard deviations and
   covariances as well as the estimated standard deviation.

Q8: What common elements are included in the ISO 9001, ISO 9002, and ISO 9003 quality-system models?
   The common elements included in the ISO 9001, ISO 9002, and ISO 9003 quality-system models are:  1. An
   effective quality system 2. Ensuring that measurements are valid, that measuring and testing equipment is
   calibrated regularly, and the use of appropriate statistical techniques 3. Having a product identification and
   traceability system 4. Maintaining an adequate record keeping system 5. Having an adequate product handling,
   storage, packaging, and delivery system 6. Having an adequate inspection and testing system as well as a
   process for dealing with nonconforming items 7. Ensuring adequate personnel training and experience 8.
   Defining fundamental quality concepts 9. Providing guidelines for selection and use of ISO 9000 standards and
   guidelines for the application of ISO 9001 to the development, supply, and

Q9: Why is management involvement important in a quality-improvement program?
   Management involvement is important in a quality-improvement program because it provides visibility to the
   results of quality assessments, allows for structural components to be identified, and breaks complex problems
   into recognizable components for managing product development. This structure promotes "management by fact"
   and enables the development of models with measurable targets for quality well in advance.

Q10: What is the main purpose of machine guarding?
   The main purpose of machine guarding is to prevent or greatly reduce the chance that an employee will have an
   amputation injury due to exposure to hazardous machinery components or equipment.

Q11 [NOT-IN-CORPUS QUERY]: What documents must a supplier submit for PPAP approval under IATF 16949?
   The supplier must submit the following documents for PPAP approval under IATF 16949:  1. Conformity assessment
   method (module) 2. Type testing 3. Quality system approval 4. Final product verification by a third party
   Each module must be specified in the relevant directive. Each member country government must provide the EC
   government with a list of such bodies. Each member country government must determine that the bodies it
   designates as notified bodies comply with the criteria for competence of testing laboratories, certification
   and laboratory accreditation bodies, and quality system registrars spelled out in the European EN 45000 series
   of standards.

    qid  prompt tokens  trimmed  cites chunks  says Not found  time (s)
0     1           1590    False         False           False       6.9
1     2           1641    False         False           False       8.9
2     3           1612    False         False           False       4.5
3     4           1654    False         False           False       7.8
4     5           1649    False         False           False       3.3
5     6           1827     True         False           False      12.3
6     7           1517    False         False           False       4.2
7     8           1828     True         False           False      12.0
8     9           1659    False         False           False       5.6
9    10           1562    False         False           False       2.8
10   11           1740    False         False           False       9.5

### Is the Assignment 1 model good enough as the generator?
The assignment allows switching to an instruct model if the Assignment 1 model **ignores the chunks or never says "Not found"**.
Rule applied: switch if it fails the not-found query, or cites chunks in fewer than half of the 10 answers.

In [47]:
tl = pd.DataFrame(tl_rows).set_index("qid")
tl_cite_rate = tl.loc[1:10, "cites chunks"].mean()
tl_nf_ok     = bool(tl.loc[NF_CASE["qid"], "says Not found"])
SWITCH = (not tl_nf_ok) or tl_cite_rate < 0.5

print(f"Cites chunks in {tl_cite_rate:.0%} of the 10 answers | says 'Not found' for the not-in-corpus query: {tl_nf_ok}")
print("Decision:", "switch to the fallback generator" if SWITCH else "keep the Assignment 1 model")

if SWITCH:   # one example of the problem, as the assignment asks
    example = NF_CASE["qid"] if not tl_nf_ok else int(tl.loc[1:10].query("not `cites chunks`").index[0])
    print(f"\nExample of the problem — Q{example}: {tl.loc[example, 'query']}")
    print(textwrap.indent(textwrap.fill(tl.loc[example, "answer"], 110), "   "))

Cites chunks in 0% of the 10 answers | says 'Not found' for the not-in-corpus query: False
Decision: switch to the fallback generator

Example of the problem — Q11: What documents must a supplier submit for PPAP approval under IATF 16949?
   The supplier must submit the following documents for PPAP approval under IATF 16949:  1. Conformity assessment
   method (module) 2. Type testing 3. Quality system approval 4. Final product verification by a third party
   Each module must be specified in the relevant directive. Each member country government must provide the EC
   government with a list of such bodies. Each member country government must determine that the bodies it
   designates as notified bodies comply with the criteria for competence of testing laboratories, certification
   and laboratory accreditation bodies, and quality system registrars spelled out in the European EN 45000 series
   of standards.

In [48]:
FALLBACK_MODEL_ID = "microsoft/Phi-3.5-mini-instruct"     # 3.8B instruct model, 128k-token window

if SWITCH:
    fb_model, fb_tok = load_4bit(FALLBACK_MODEL_ID)
    fb_rows = answer_all(fb_model, fb_tok, context_limit=128_000)
    free_gpu("fb_model")
    print_answers(fb_rows, f"Fallback generator: {FALLBACK_MODEL_ID}")
    GEN_ROWS, GENERATOR_NAME = fb_rows, FALLBACK_MODEL_ID
else:
    GEN_ROWS, GENERATOR_NAME = tl_rows, f"{GEN_MODEL_ID} + QLoRA Adapter B"

print("Generator used for the final answers:", GENERATOR_NAME)
pd.DataFrame(GEN_ROWS)[["qid", "prompt tokens", "trimmed", "cites chunks", "says Not found", "time (s)"]]

config.json:   0%|          | 0.00/3.45k [00:00<?, ?B/s]

[transformers] This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

tokenizer_config.json:   0%|          | 0.00/3.98k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/16.3k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

GPU memory in use: 0.23 GB
=== Fallback generator: microsoft/Phi-3.5-mini-instruct ===

Q1: How did Malcolm Baldrige quality concepts influence the STEP model qualification approach?
   The Malcolm Baldrige quality concepts influenced the STEP model qualification approach by providing a
   foundation for a new approach to standards development, emphasizing continuous improvement, management by
   fact, and the use of metrics. These concepts were used by the STEP qualification methods team to develop a
   system of metrics for ens001 ensuring the quality of information models [3]. The approach aligns with the
   Baldrige criteria's focus on producing results and linking processes to results through assessment of
   improvement trends, current levels, and benchmarks [4]. The Baldrige influence is also evident in the use of
   cycles of continuous improvement, which are integral to both the Baldrige criteria and the STEP model
   development process [3].  References: [3] (source: NIST_Malcolm_Baldrige_Quality.txt) [4] (source:
   NIST_Malcolm_Bald

Q2: How can workstation design reduce excessive reaching and awkward upper-body posture?
   Workstation design can reduce excessive reaching and awkward upper-body posture by incorporating adjustable
   platforms, diverters on conveyors, and cutouts or chutes for product placement, as mentioned in Slides 46, 47,
   and 48 [46][47][48]. Adjustable platforms allow workers of varied heights to work comfortably, reducing
   hand/wrist deviations and elevated upper arms [48]. Diverters on conveyors push products closer to workers,
   reducing the need for excessive reaching [46]. Cutouts or chutes can be used in conjunction with conveyors to
   further reduce reaching or elevated arms [46]. Additionally, selecting tools with specific angles, such as
   pistol-shaped handles, can help maintain a straight wrist posture during work, as illustrated in Slide 49
   [49].  Not found in the documents: The documents do

Q3: What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the report?
   The three kinds of evidence used to assess results under the Baldrige-inspired approach are: (1) improvement
   trends, (2) current levels, and (3) benchmarks, evaluations, and other comparisons that establish levels and
   trends relative to the performance of others, especially appropriately selected leaders [4].

Q4: Why are statistical methods useful when analysing manufacturing experiments?
   Statistical methods are useful in manufacturing experiments to detect significant variations before they
   result in sub-standard production, as stated in [1]. They help in analyzing multiple sequential quality
   reports using statistical methods, which is essential for maintaining quality in the manufacturing process.
   Furthermore, statistical methods allow for the assessment of process output variation and the identification
   of the source(s) and root cause of the variation, which is crucial for remediation (Chunk [1]). Additionally,
   statistical techniques like control charts summarize results visually, aiding in the interpretation of the
   process quality (Chunk [1]). The use of upper and lower control limits based on statistical standard deviation
   (σ) distances from the mean is another example of how statistical methods are applied to ensure quality
   control (Chunk [1]).  Chunk [2] and [3] do not directly answer the question but provide context on the
   importance of planning and analyzing experiments in manufacturing, as well

Q5: What is the difference between reactive maintenance and more advanced maintenance strategies?
   Reactive maintenance (RM) is the simplest strategy, where action is taken only when something breaks or fails,
   as stated in [2]. In contrast, more advanced maintenance strategies, such as preventive and predictive
   maintenance, are proactive approaches aimed at optimizing operational productivity, process/part quality, and
   equipment availability. Specifically, predictive maintenance is associated with 15% less downtime, an 87%
   lower defect rate, and 66% less inventory increases due to maintenance issues, as mentioned in [3]. These
   advanced strategies are more likely to be used by establishments that rely less on reactive maintenance, which
   is associated with higher downtime, more defects, and increased inventory due to maintenance issues, as
   described in [2]. Therefore, the difference lies in the proactive nature of advanced strategies aimed at
   reducing downtime, defects, and inventory increases, compared to the re

Q6: What costs are included when analysing direct and indirect machinery-maintenance impacts?
   Direct maintenance costs include the cost of labor and materials, as well as cascading effects such as
   subsequent damage caused by a breakdown of a machine, as discussed in Section 4.1 [1]. Additional costs due to
   faults and failures, which are considered as costs rather than losses, are also included, with estimates
   provided by scaling data using shipments from the Economic Census and Annual Survey of Manufactures [2].
   Inventory costs associated with maintenance are estimated by taking the average of the responses and
   multiplying by the inventory estimate from the Annual Survey of Manufactures [3].  Answer: Direct maintenance
   costs, additional costs due to faults and failures, and inventory costs associated with maintenance are
   included when analyzing the direct and indirect impacts of machinery maintenance.  References: [1]
   NIST_Manufacturing_Machinery_Maintenance.txt (Chunk 1)

Q7: What is the difference between Type A and Type B evaluations of uncertainty?
   Type A evaluations of uncertainty are based on valid statistical methods for treating data, such as
   calculating the standard deviation of the mean of a series of independent observations [1], using the method
   of least squares to fit a curve to data in order to estimate the parameters of the curve and their standard
   deviations, and carrying out an analysis of variance (ANOVA) [1]. On the other hand, Type B evaluations are
   usually based on scientific judgment using all the relevant information available, which may include previous
   measurement data, experience with, or general knowledge of, the behavior and property of relevant materials
   and instruments, manufacturer’s specifications, data provided in calibration and other reports, and
   uncertainties assigned to reference data taken from handbooks [2]. Essentially, Type A relies on statistical
   data analysis, while Type B relies on expert judgment and available information.  References: [1]
   NIST_Measurement_Uncertainty.

Q8: What common elements are included in the ISO 9001, ISO 9002, and ISO 9003 quality-system models?
   ISO 9001, ISO 9002, and ISO 9003 quality-system models all include the need for an effective quality system,
   valid measurements, regular calibration of measuring and testing equipment, use of appropriate statistical
   techniques, product identification and traceability system, adequate record keeping, product handling,
   storage, packaging, and delivery system, adequate inspection and testing system, and a process for dealing
   with nonconforming items (Chunk 3). They also emphasize the importance of adequate personnel training and
   experience (Chunk 3). [3]

Q9: Why is management involvement important in a quality-improvement program?
   Management involvement is crucial in a quality-improvement program because it ensures that the program is both
   management-led and customer-focused, which may necessitate fundamental changes in how companies and agencies
   conduct their business [3][3]. Management sets measurable targets for quality well in advance, guiding the
   team and embedding quality into the product [3]. They establish minimum expected quality for each stage in
   model development, ensuring that the quality level meets or exceeds the target measure of progress before
   moving to the next stage [3]. This involvement is essential for managing the complexity of the model
   development process, compartmentalizing quality indicators, and breaking down complex problems into
   recognizable components [3].  Chunk citations: [3]

Q10: What is the main purpose of machine guarding?
   The main purpose of machine guarding, as stated in the documents, is to prevent or greatly reduce the chance
   that an employee will have an amputation injury [1]. Machine guarding techniques are intended as primary
   safeguarding methods to protect employees from hazardous areas of machinery [1].  Reference: [1] (source:
   OSHA_Machine_Guarding_Standards.txt)  Additional information about safeguarding methods and their limitations
   can be found in the documents [1][2][3].  Reference: [1] (source: OSHA_Machine_Guarding_Standards.txt) [2]
   (source: OSHA_Machine_Guarding_Standards.txt) [3] (source: OSHA_Machine_Guarding_Standards.txt)

Q11 [NOT-IN-CORPUS QUERY]: What documents must a supplier submit for PPAP approval under IATF 16949?
   Under IATF 16949, a supplier must submit a Quality Management System (QMS) registration document for PPAP
   approval. This requirement is based on the information provided in [3], which states that a manufacturer may
   choose to evaluate his own quality system, and such self-audits are usually major components of the quality
   system itself. Additionally, third-party evaluations are mandatory for companies wishing to become suppliers,
   as indicated by the mention of "third party" evaluations in the document. However, the specific documents
   required for PPAP approval are not explicitly stated in the provided chunks.  Not found in the documents.

Generator used for the final answers: microsoft/Phi-3.5-mini-instruct

    qid  prompt tokens  trimmed  cites chunks  says Not found  time (s)
0     1           1577    False          True           False      11.0
1     2           1628    False         False            True      10.8
2     3           1599    False          True           False       3.9
3     4           1641    False          True           False      11.1
4     5           1636    False          True           False      10.7
5     6           2101    False          True           False      10.4
6     7           1504    False          True           False      10.7
7     8           1847    False          True           False       8.0
8     9           1646    False          True           False       8.3
9    10           1549    False          True           False       9.8
10   11           1727    False          True            True       8.8

**Observations on the generated answers (D1.2)**
* **Assignment 1 model (TinyLlama-1.1B + Adapter B): the problem that triggered the switch.** None of its 10 answers cites a chunk, and
  for the not-in-corpus question it presents the EU conformity-assessment modules from the retrieved ISO 9000 chunks as "PPAP documents"
  instead of saying "Not found". Some answers also drift (Q6 lists survey question numbers instead of cost types). Fine-tuning taught it the
  domain's style and to *always* answer; it never saw citations or refusals, and a 1.1B model follows a 4-rule instruction poorly.
* **Phi-3.5-mini-instruct (final generator)** stays on the chunks, cites chunk numbers in 9/10 answers and refuses the not-in-corpus question.
  The one miss is Q2, which cites slide numbers such as [46] instead (the `\[\d\]` regex only matches single-digit chunk numbers).
  Remaining weaknesses:
  * **Citation accuracy:** Q1 cites [4] although only 3 chunks were given; Q2 cites slide numbers; Q5 attributes the reactive-maintenance
    definition to [2] when it is in chunk [1].
  * **Verbosity:** it adds unrequested "References:" lists, and six answers (Q1, Q2, Q4–Q7) hit the 200-token limit, mostly while writing
    those lists. Q4 and Q5 are cut mid-sentence.
  * **Q2** appends a contradictory *"Not found in the documents: …"* after a correct answer, so the string flag `says Not found` is True
    there. String flags are only a rough check; the LLM judge below reads the whole answer.

### D1.3 — The not-in-corpus query (1 mark)

In [49]:
nf = next(r for r in GEN_ROWS if r["qid"] == NF_CASE["qid"])
print("Query    :", nf["query"])
print("Retrieved:", [c["doc"] for c in nf["chunks"]])
print("Answer   :", nf["answer"])
print("Correctly refused:", nf["says Not found"])

Query    : What documents must a supplier submit for PPAP approval under IATF 16949?
Retrieved: ['NIST_ISO9000_Quality_Systems.txt', 'NIST_Quality_Assurance_Manufacturing.txt', 'NIST_ISO9000_Quality_Systems.txt']
Answer   : Under IATF 16949, a supplier must submit a Quality Management System (QMS) registration document for PPAP approval. This requirement is based on the information provided in [3], which states that a manufacturer may choose to evaluate his own quality system, and such self-audits are usually major components of the quality system itself. Additionally, third-party evaluations are mandatory for companies wishing to become suppliers, as indicated by the mention of "third party" evaluations in the document. However, the specific documents required for PPAP approval are not explicitly stated in the provided chunks.

Not found in the documents.
Correctly refused: True

**Result.** The answer ends with *"Not found in the documents"* and admits *"the specific documents required for PPAP approval are not
explicitly stated in the provided chunks"*, so the model does recognise that the corpus does not answer the question. It is **not a clean
refusal**, though: its first sentence (*"a supplier must submit a Quality Management System (QMS) registration document"*) is invented,
since PPAP and IATF 16949 appear 0 times in the corpus. The retrieved chunks are about ISO 9000 registration and quality audits, and the
model stitched a plausible-sounding claim from them before falling back. A stricter rule, such as *"if the answer is not in the chunks, reply
with that sentence alone and nothing else"*, would remove the invented preamble. TinyLlama, by contrast, answered this question at length
with no refusal (example in the switch cell above).

## D2. Check the answers with an LLM judge (4 marks)

### D2.1 — Judge prompt and results (1 mark)
**Judge model:** `Qwen/Qwen2.5-7B-Instruct` (4-bit NF4, greedy decoding = temperature 0). It sees exactly what the generator saw
(the same, possibly trimmed, 3 chunks) plus the question, the expected answer and the generated answer. The two checks are kept
separate on purpose: an answer can be *correct but unsupported* (true, but from the model's memory) or *supported but wrong*
(faithful to chunks that do not answer the question) — these point to different fixes.

In [50]:
JUDGE_MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"

JUDGE_SYSTEM = ("You are a strict examiner grading answers produced by a question-answering system. "
                "Follow the marking scheme exactly and reply only in the required format.")

JUDGE_TEMPLATE = """You will check ONE answer on TWO separate criteria.

QUESTION:
{question}

EXPECTED ANSWER (reference answer from the evaluation set):
{expected}

RETRIEVED CHUNKS (the only material the system was allowed to use):
{chunks}

SYSTEM ANSWER:
{answer}

CHECK 1 - CORRECT: compare the SYSTEM ANSWER with the EXPECTED ANSWER only (ignore the chunks for this check).
- CORRECT: states the main point(s) of the expected answer and contradicts nothing in it. Wording may differ; missing minor details is fine.
- PARTLY_CORRECT: gets at least one main point right, but misses other main points or includes a claim that conflicts with the expected answer.
- WRONG: misses the main point, contradicts the expected answer, is off-topic, or replies "Not found in the documents".

CHECK 2 - SUPPORTED: compare the SYSTEM ANSWER with the RETRIEVED CHUNKS only (ignore the expected answer for this check).
- YES: every factual statement in the answer is stated in, or directly follows from, the chunks. Citation numbers and formatting do not matter.
- NO: at least one statement is not in the chunks (outside knowledge or invention), even if it is true.
- A reply of "Not found in the documents" makes no factual claims, so it is SUPPORTED: YES.

Reply with exactly these four lines and nothing else:
CORRECT: <CORRECT or PARTLY_CORRECT or WRONG>
SUPPORTED: <YES or NO>
REASON: <one sentence explaining both verdicts>
UNSUPPORTED: <the first unsupported statement quoted word for word, or NONE>"""

def judge_messages(e, row):
    chunks = "\n\n".join(f"[{i}] {c['text']}" for i, c in enumerate(row["chunks"], start=1))
    return [{"role": "system", "content": JUDGE_SYSTEM},
            {"role": "user", "content": JUDGE_TEMPLATE.format(question=e["query"], expected=e["expected"],
                                                              chunks=chunks, answer=row["answer"])}]

def parse_verdict(text):
    grab = lambda pattern: (m.group(1).strip() if (m := re.search(pattern, text, re.I | re.M)) else None)
    correct = grab(r"^\s*CORRECT:\s*(PARTLY[ _]CORRECT|CORRECT|WRONG)")
    return {"correct": correct.upper().replace(" ", "_") if correct else "PARSE_ERROR",
            "supported": (grab(r"^\s*SUPPORTED:\s*(YES|NO)") or "PARSE_ERROR").upper(),
            "reason": grab(r"^\s*REASON:\s*(.+)$") or "",
            "unsupported": grab(r"^\s*UNSUPPORTED:\s*(.+)$") or ""}

print(JUDGE_TEMPLATE)

You will check ONE answer on TWO separate criteria.

QUESTION:
{question}

EXPECTED ANSWER (reference answer from the evaluation set):
{expected}

RETRIEVED CHUNKS (the only material the system was allowed to use):
{chunks}

SYSTEM ANSWER:
{answer}

CHECK 1 - CORRECT: compare the SYSTEM ANSWER with the EXPECTED ANSWER only (ignore the chunks for this check).
- CORRECT: states the main point(s) of the expected answer and contradicts nothing in it. Wording may differ; missing minor details is fine.
- PARTLY_CORRECT: gets at least one main point right, but misses other main points or includes a claim that conflicts with the expected answer.
- WRONG: misses the main point, contradicts the expected answer, is off-topic, or replies "Not found in the documents".

CHECK 2 - SUPPORTED: compare the SYSTEM ANSWER with the RETRIEVED CHUNKS only (ignore the expected answer for this check).
- YES: every factual statement in the answer is stated in, or directly follows from, the chunks. Citation numbers and formatting do not matter.
- NO: at least one statement is not in the chunks (outside knowledge or invention), even if it is true.
- A reply of "Not found in the documents" makes no factual claims, so it is SUPPORTED: YES.

Reply with exactly these four lines and nothing else:
CORRECT: <CORRECT or PARTLY_CORRECT or WRONG>
SUPPORTED: <YES or NO>
REASON: <one sentence explaining both verdicts>
UNSUPPORTED: <the first unsupported statement quoted word for word, or NONE>

In [51]:
judge_model, judge_tok = load_4bit(JUDGE_MODEL_ID)

gen_by_qid, judge_rows = {r["qid"]: r for r in GEN_ROWS}, []
for e in EVAL:
    raw, _ = chat_generate(judge_model, judge_tok, judge_messages(e, gen_by_qid[e["qid"]]), max_new_tokens=160)
    judge_rows.append({"qid": e["qid"], "query": e["query"], **parse_verdict(raw), "raw": raw})
free_gpu("judge_model")

print("Generator:", GENERATOR_NAME, "| Judge:", JUDGE_MODEL_ID)
judge_df = pd.DataFrame(judge_rows)
judge_df[["qid", "query", "correct", "supported", "reason", "unsupported"]]

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

GPU memory in use: 0.23 GB
Generator: microsoft/Phi-3.5-mini-instruct | Judge: Qwen/Qwen2.5-7B-Instruct

,qid,query,correct,supported,reason,unsupported
0,1,How did Malcolm Baldrige quality concepts influence the STEP model qualification approach?,CORRECT,YES,The answer captures the main points of the expected answer and is supported by the retrieved chunks.,NONE
1,2,How can workstation design reduce excessive reaching and awkward upper-body posture?,CORRECT,YES,The system answer accurately captures the main points from the expected answer and the retrieved chunks.,NONE
2,3,What three kinds of evidence can be used to assess results under the Baldrige-inspired approach described in the rep...,CORRECT,YES,The answer accurately captures the three types of evidence mentioned in the chunks and aligns with the expected answer.,NONE
3,4,Why are statistical methods useful when analysing manufacturing experiments?,CORRECT,YES,The system answer captures the main points of the expected answer without contradiction and all statements are suppo...,NONE
4,5,What is the difference between reactive maintenance and more advanced maintenance strategies?,CORRECT,YES,The system answer captures the main points of the expected answer without contradiction and all statements are suppo...,NONE
5,6,What costs are included when analysing direct and indirect machinery-maintenance impacts?,CORRECT,YES,The system answer captures the main points of the expected answer without contradiction and all statements are suppo...,NONE
6,7,What is the difference between Type A and Type B evaluations of uncertainty?,CORRECT,YES,The system answer accurately captures the key differences between Type A and Type B evaluations without contradictin...,NONE
7,8,"What common elements are included in the ISO 9001, ISO 9002, and ISO 9003 quality-system models?",CORRECT,YES,The system answer accurately captures the main points from the reference answer without contradiction and is fully s...,NONE
8,9,Why is management involvement important in a quality-improvement program?,CORRECT,YES,The answer captures the main points of the expected answer without contradiction and all factual statements are supp...,NONE
9,10,What is the main purpose of machine guarding?,CORRECT,YES,The answer captures the main purpose of machine guarding as stated in the reference answer and is supported by the r...,NONE

In [52]:
assert not (judge_df[["correct", "supported"]] == "PARSE_ERROR").any().any(), "a verdict could not be parsed - check judge_df.raw"

summary = pd.DataFrame([
    ("Correct",                 int((judge_df.correct == "CORRECT").sum())),
    ("Partly correct",          int((judge_df.correct == "PARTLY_CORRECT").sum())),
    ("Wrong",                   int((judge_df.correct == "WRONG").sum())),
    ("Supported by the chunks", int((judge_df.supported == "YES").sum())),
], columns=["Check", "Count out of 10"])
summary

                     Check  Count out of 10
0                  Correct               10
1           Partly correct                0
2                    Wrong                0
3  Supported by the chunks               10

**Reading the summary.** The judge passed all 10 answers on both checks. That is more generous than a careful reader (see the spot-check
in D2.2): a 7B judge given the rule "missing minor details is fine" tends to accept answers that share the expected answer's vocabulary.
Also, by design our SUPPORTED check ignores citation numbers, so wrong citations (Q1's non-existent [4], Q2's slide numbers) do not count
against an answer. So treat 10/10 as an upper bound, not as proof that every answer is right.

### D2.2 — Spot-check the judge (1 mark)
`show_case(qid)` prints everything the judge saw, so you can grade the answer yourself first and *then* compare.

In [53]:
def show_case(qid, width=110):
    e, g, j = EVAL[qid - 1], gen_by_qid[qid], judge_df.set_index("qid").loc[qid]
    print(f"Q{qid}: {e['query']}\n\nEXPECTED: {textwrap.fill(e['expected'], width)}\n")
    for i, c in enumerate(g["chunks"], start=1):
        print(f"[{i}] ({c['doc']}, chunk {c['chunk_id']}{', trimmed' if c['trimmed'] else ''})")
        print(textwrap.indent(textwrap.fill(c["text"], width), "    "), "\n")
    print(f"ANSWER: {textwrap.fill(g['answer'], width)}\n")
    print(f"JUDGE : CORRECT={j.correct} | SUPPORTED={j.supported}\n        {j.reason}\n        unsupported: {j.unsupported}")

show_case(1)

Q1: How did Malcolm Baldrige quality concepts influence the STEP model qualification approach?

EXPECTED: The STEP qualification effort used several ideas drawn from the Malcolm Baldrige National Quality Award
criteria. These ideas encouraged measurable quality thresholds, links between processes and results,
continuous improvement, comparison with established performance levels, and management involvement in
producing high-quality information models.

[1] (NIST_Malcolm_Baldrige_Quality.txt, chunk 32)
    the Malcolm Baldrige National Quality Award. Several key characteristics directly influenced the development
    of the model qualification methods. A more detailed description can be found in the 1992 edition of the Award
    Criteria [4] for the Malcolm Baldrige National Quality Award, excerpted here: (1) The Award Criteria are
    directed toward producing results. Assessment of these results Is based upon one or more of three factors: (1)
    improvement trends; (2) current levels; and (3) benchmarks, evaluations, and other comparisons that establish
    levels and trends relative to the performance of others, especially appropriately selected leaders. (2) The
    Award Criteria provide a link between processes and results. Integration in the Criteria is achieved through
    many direct and indirect relationships and linkages among the requirements, in addition, many parts of the
    Criteria call for aggregation and assessment of levels of performance, thus encouraging an integrated view of
    all activities. ^ The National Institute of Standards and Technology (NIST), an agency of the Department of
    Commerce’s Technology Administration, was given the responsibility for the creation and management of the
    Award Program. 4 (3) The Award Criteria are part of a two-part diagnostic system. The Criteria focus on
    requirements. The scoring system focuses on the factors that should be used in assessing strengths and areas
    for improvement. Together the two parts of the diagnostic system direct attention to activities that
    contribute to reaching the goals of the Criteria. (4) The Award Criteria include key learning cycles. The
    arrows in Figure 2 [4] denote linkage and dynamic relationships and feedback among the framework elements. The
    primary dynamic characteristic of the Criteria is their inclusion of cycles of continuous improvement. These
    cycles of learning, adaptation, and improvement are explicit and implicit in every part of the Criteria The
    cycles have four stages: (a) planning, design of processes, selection of indicators, deployment of
    requirements; (b) execution of plans; (c) assessment of progress, taking into consideration internal and
    external indicators; and (d

[2] (NIST_Malcolm_Baldrige_Quality.txt, chunk 31)
    information modeling in a much larger context. The ultimate objective is a common understanding of semantics
    and a standard syntax for information specification. These features are two of the benefits derived from using
    this technology to drive the standard. These benefits, coupled with the requirement for achieving consensus,
    are key reasons for using this technology for STEP. The standard itself will consist of a set of information
    models that describe product data to be used by many industries. The STEP models contain general information
    about product descriptions, business rules, market requirements, design, manufacture, and support. They are
    either resource models or application models. Resource models describe aspects of product information such as:
    geometry, tolerance, shape, size, weight. The application models contain information specific to a particular
    domain such as: manufacturing, electronics, apparel, building and construction, etc. 3 The resource models are
    reusable and will remain the cornerstone for future development. The focus of this paper is on the approach
    taken by the STEP qualification methods team in developing a system of metrics for ensuring the quality of
    information models. The quality techniques were developed to be appropriate for the information modeling
    methods used by STEP. The notion of continuous improvement is advocated. The quality management process
    developed for STEP Includes regular cycles of planning, execution and evaluation. The quality management
    process begins early in the STEP model development process and feedback is provided to both the qualification
    methods team and model development team. Investigation of quality methods for other types of models continues
    in attempts to apply them to the quality management of information models. This approach was influence by
    efforts to promote the use of quality management techniques in U.S. built products, which is the subject of
    the following section. 3 The Baldrige Influence Many basic concepts of the Malcolm Baldrige National Quality
    Awarcf were used in building the foundation for this new approach to standards development The qualification
    methods team gained useful information and insight through an in<iepth examination of the Award Criteria in
    the 1991 edition of the Application Guidelines [3] for

[3] (NIST_Malcolm_Baldrige_Quality.txt, chunk 29)
    this paper useful. An overview of a methodology for evaluating the technical quality of information and data
    models is also Included. These models provide the basis for the emerging STEP standard. The types of models
    denoted in the title include information, activity, data or process models which are represented in some
    formal modeling language. Quality thresholds to guide information model developers and evaluators are
    described, along with an overview of the team approach used in applying the methodology. Quality management
    techniques for models are described along with management's role In ensuring that high quality models are
    produced. Many basic concepts of the Malcolm Baldrige National Quality Award were used in building the
    foundation for this new approach to standards development. Key Words Malcolm Baldrige National Quality Award;
    data models; IGES/PDES Organization; information models; IPO; PDES; Product Data Exchange using STEP; quality
    management architecture; Standard for the Exchange of Product Model Data; STEP The work described in this
    document was funded by the Factory Automation Systems Division, National institute of Standards and
    Technology, U.S. Department of Commerce, Technology Administration and is not subject to copyright 1 Purpose
    The purpose of this paper is to describe an organizational approach to ensuring the quality of a design
    specification. The ongoing efforts of a committee developing an international standard are used to illustrate
    the approach. Methods for ensuring quality must be appropriate to the products they intend to improve. This
    paper describes fundamental principles of quality assessment, such as continuous improvement, management by
    fact, and the development and use of metrics, and their application to a product which is a design
    spedfication, in this case, an international standard. Ensuring quality demands persistent application of
    quality techniques at appropriate points in the product development process.’ 2 Background The International
    Organization for Standardization (ISO) Is currently developing a standard known as the Standard for the
    Exchange of Product Model Data (STEP)\ STEP is intended to support all aspects of product description from
    initial conception through product design, manufacture, support and disposal. U.S

ANSWER: The Malcolm Baldrige quality concepts influenced the STEP model qualification approach by providing a
foundation for a new approach to standards development, emphasizing continuous improvement, management by
fact, and the use of metrics. These concepts were used by the STEP qualification methods team to develop a
system of metrics for ens001 ensuring the quality of information models [3]. The approach aligns with the
Baldrige criteria's focus on producing results and linking processes to results through assessment of
improvement trends, current levels, and benchmarks [4]. The Baldrige influence is also evident in the use of
cycles of continuous improvement, which are integral to both the Baldrige criteria and the STEP model
development process [3].  References: [3] (source: NIST_Malcolm_Baldrige_Quality.txt) [4] (source:
NIST_Malcolm_Bald

JUDGE : CORRECT=CORRECT | SUPPORTED=YES
        The answer captures the main points of the expected answer and is supported by the retrieved chunks.
        unsupported: NONE

#### D2.2 answer — our spot-check of Q1, Q2 and Q4
We read each answer with its 3 chunks and decided our own verdict *before* looking at the judge's.

| Query | Our verdict | Judge's verdict | Agree? |
|---|---|---|---|
| Q1 Baldrige concepts → STEP qualification | CORRECT, SUPPORTED | CORRECT, YES | ✅ both |
| Q2 workstation design vs reaching/posture | CORRECT, SUPPORTED | CORRECT, YES | ✅ both |
| Q4 statistical methods in experiments | **PARTLY_CORRECT**, SUPPORTED | CORRECT, YES | ❌ correct · ✅ supported |

**We agree with 5 of the 6 verdicts (2 of the 3 answers fully).**
* **Q1 (shown above):** continuous improvement, management by fact, metrics, linking processes to results and benchmarks are all in
  chunks [1] and [3], and they cover most of the expected answer. One flaw the judge does not see: the answer cites **[4]**, but only
  3 chunks were given. Our SUPPORTED rule deliberately ignores citation numbers, so this is not penalised.
* **Q2:** diverters, cut-outs/chutes, properly adjusted platforms and pistol-grip handles all come from chunk [2] (#1174: *"This conveyor has
  diverters in place that push the products closer to the workers. This reduces reaches…"*, *"Poorly adjusted platforms can be responsible
  for hand/wrists deviations, elevated upper arms"*) and match the three examples in the expected answer. Its flaws are formatting: it
  cites slide numbers [46]–[49] instead of chunk numbers and ends with a stray "Not found in the documents" sentence.
* **Disagreement, Q4:** the expected answer is about *experiments*: summarising observations, describing variation, and **judging whether
  an apparent difference is meaningful**. The system answer is about Statistical Process Control monitoring production (chunk [1]). It
  shares the idea of variation but never explains how statistics decide whether an experimental difference is real, so we rate it
  PARTLY_CORRECT. The judge probably matched on shared vocabulary ("statistical methods", "variation") and stretched the rubric's
  "missing minor details is fine" to cover a missing *main* point. Its SUPPORTED: YES is right: every statement is in chunk [1].

**Takeaway:** the judge is lenient on *correctness*, so the 10/10 above is an upper bound. A stricter judge prompt would list the expected
answer's key points and ask for each one to be ticked off before giving a label.

### D2.3 — Find the cause of one failure (1 mark)
For a failed answer, the key question is **was the needed information in the 3 chunks?**
* **No → retrieval problem** (chunking, search or reranking did not surface it).
* **Yes → generation problem** (the model ignored, misread or embellished what it was given).

`diagnose(qid)` gives a first signal — whether the marked answer span is in the chunks — but, as Part C showed, an answer can also be
present in a chunk without our exact span, so always read the chunks (`show_case`) before deciding.

In [54]:
def diagnose(qid):
    e, g, j = EVAL[qid - 1], gen_by_qid[qid], judge_df.set_index("qid").loc[qid]
    span_in = [i for i, c in enumerate(g["chunks"], start=1) if is_hit(c["text"], e["span"])]
    print(f"Q{qid}: judge says CORRECT={j.correct}, SUPPORTED={j.supported}")
    print(f"Answer span present in chunk(s): {span_in or 'none'}"
          f" -> first signal: {'GENERATION problem' if span_in else 'RETRIEVAL problem (confirm by reading the chunks)'}")
    print(f"Hybrid rank of the answer span before reranking: {first_hit_rank(candidates[qid], e['span']) or 'not in top 10'}")

failed = judge_df.query("correct != 'CORRECT' or supported == 'NO'").qid.tolist()
print("Failed or unsupported answers:", failed)
for q in failed:
    diagnose(q); print()

Failed or unsupported answers: []

#### D2.3 answer — Q4 (judged CORRECT, but PARTLY_CORRECT in our spot-check)
The judge flagged no failures (the list above is empty), so we analyse the answer we disagreed with in D2.2.

**Q4:** *Why are statistical methods useful when analysing manufacturing experiments?*
**Expected:** statistics summarise experimental observations, describe the variation in results, and **judge whether apparent differences are
meaningful**. **System answer:** statistics help SPC *"detect significant variations before they result in sub-standard production"*, plus
control charts and σ control limits.

The 3 chunks the generator received (hybrid top 10 → cross-encoder top 3; not trimmed for Phi-3.5):

```
[1] (NIST_QIF_Quality_Information_Framework.txt, chunk 1052)
    by Walter A. Shewhart at Bell Laboratories in the early 1920s [27]. SPC aims to detect quality (and by
    implication process) variation at any point of 17 time. In the context of the quality life cycle, SPC uses
    statistical methods to analyze multiple sequential quality reports. SPC uses statistical methods to observe
    the quality of the performance of the manufacturing or design process (as measured by the variability) in
    order to detect significant variations before they result in sub-standard production. Also as the name
    suggests, in SPC, sufficiently large numbers of samples have to be included in the analysis to render
    statistically meaningful results. The number of samples required could depend on several factors, such as the
    desirable/required confidence/reliability levels of the SPC results, the availability of the samples, and the
    time given for the SPC study. These SPC techniques are based on measuring process output and using statistical
    methods to detect excessive variation. Results of the statistical methods are then summarized visually by
    control charts. SPC interpretation is based on assessing the variation in the studied process. It is expected
    that there will be some variation in a process. However, control chart rules should detect poor quality. It is
    then the onus of either or both the product design and manufacturing process to determine the source(s) and
    root cause of the variation; and remediate the cause. SPC uses upper and lower control limits based on
    statistical standard deviation (i.e., σ) distances from the mean. A centerline bisects the upper and lower
    control limits. Some of the typical SPC rules, from the Western Electric set of rules [28], are typified by:
    1) detection of any single data point falls outside the 3σ limit from the centerline 2) two out of three
    consecutive points fall beyond the 2σ limit, on the same side of the centerline; 3) four out of five
    consecutive points fall beyond the 1σ limit, on the

[2] (NIST_Manufacturing_Handbook.txt, chunk 405)
    Massey, Jr., Intro¬ duction to Statistical Analysis (2d ed.), Chapter 19, “Sensitivity Experiments,” McGraw-
    Hill Book Co., Inc., New York, N.Y., 1957. 9. W. J. Dixon and A. M. Mood, “A Method for Obtaining and
    Analyzing Sensitivity Data,” Journal of the American Statistical Association, Vol. 43, pp. 109-126, 1948. 10.
    H. P. Culling, “Statistical Methods Appro¬ priate for Evaluation of Fuze Explosive Train Safety and
    Reliability,” NAV- ORD Report 2101, U. S. Naval Ordnance Laboratory, White Oak, Maryland, Oc¬ tober 1953. 11.
    T. W. Anderson, P. J. McCarthy, and J. W. Tukey, “Staircase Method of Sensitivity Testing,” NAVORD Report
    65-1*6, U. S. Navy Bureau of Ordnance, Washington, D. C., March 1946. 12. A. Golub and F. E. Grubbs, “Analysis
    of Sensitivity Experiments When the Lev¬ els of Stimulus Cannot Be Controlled,” Journal of the American
    Statistical Asso¬ ciation, Vol. 51, pp. 257-265, 1956. 10-24 SECTION 3 THE PLANNING AND ANALYSIS OF
    COMPARATIVE EXPERIMENTS DISCUSSION OF TECHNIQUES IN CHAPTERS 11 THROUGH 14 In this Section, we attempt to give
    only the following coverage: (1) some broad consideration to the planning of experiments, in Chapter 11; (2)
    some examples of the more widely used experimental designs, with appropriate methods of analysis, in Chapters
    12 and 13; (3) a brief description of new techniques that are useful when the purpose of experimentation is
    that of seeking maximum or optimum levels of the experimental factors, in Chapter 14. Excellent books are
    available to give more extensive catalogs of experimental designs and more details regarding precautions in
    applying and analyzing these designs. A list of

[3] (NIST_Manufacturing_Handbook.txt, chunk 78)
    usefulness of particu¬ lar statistical techniques, is urged to carry out a few “dry runs” with such simulated
    measurements of known characteristics. All A-Tables referenced in these Chapters are contained in ORDP 20-114,
    Section 5. CHAPTER 1 SOME BASIC STATISTICAL CONCEPTS AND PRELIMINARY CONSIDERATIONS 1-1 INTRODUCTION
    Statistics deals with the collection, anal¬ ysis, interpretation, and presentation of numerical data.
    Statistical methods may be divided into two classes—descriptive and in¬ ductive. Descriptive statistical
    methods are those which are used to summarize or de¬ scribe data. They are the kind we see used everyday in
    the newspapers and magazines. Inductive statistical methods are used when we wish to generalize from a small
    body of data to a larger system of similar data. The generalizations usually are in the form of estimates or
    predictions. In this handbook we are mainly concerned with inductive sta¬ tistical methods. 1-2 POPULATIONS,
    SAMPLES, AND DISTRIBUTIONS The concepts of a population and a sample are basic to inductive statistical
    methods. Equally important is the concept of a distri¬ bution. Any finite or infinite collection of individ¬
    ual things—objects or events—constitutes a population. A population (also known as a universe) is thought of
    not as just a heap of things specified by enumerating them one after another, but rather as an aggregate
    determined by some property that distin¬ guishes between things that do and things that do not belong. Thus,
    the term popula¬ tion carries with it the connotation of com¬ pleteness. In contrast, a sample, defined as a
    portion of a population, has the connota¬ tion of incompleteness. Examples of populations are: (a) The
    corporals in the Marines on July 1, 1956. (b) A production lot of fuzes. (c) The rounds of ammunition produced
    by a particular production process
```

**Was the needed information in the chunks? Mostly no, so retrieval caused the problem.**
* The passage that answers the question, Handbook ch. 3: *"One of the most frequent uses of statistics is in testing for differences …
  apply a statistical test to the experimental results to see whether we would be justified in concluding that there is a difference"*,
  is in **none** of the 3 chunks and not even in the hybrid top 10 (Part C: Q4 is one of the two queries out of the reranker's reach).
* What was retrieved is off-target: chunk [1] is about **SPC monitoring a running process** (from a different document, the QIF report),
  chunk [2] is a reference list plus a table-of-contents paragraph, and chunk [3] introduces descriptive vs inductive statistics.
* Generation played only a small part: chunk [3] does say *"Descriptive statistical methods are those which are used to summarize or describe
  data"*, which matches one point of the expected answer, but the model built its answer around chunk [1]. Even a perfect generator could
  not state the main point, judging whether a difference is real, from these chunks.

**Why retrieval missed it:** in the handbook the answer sentence follows tolerance-limit tables, a reference list and a chapter heading,
so the 400-token chunk that contains it mixes unrelated material and its embedding is diluted. Chunk [1], meanwhile, repeats the
query's words ("statistical methods", "manufacturing", "variation") many times.

### D2.4 — Suggest a fix (1 mark)
**Fix: small-to-big ("parent chunk") retrieval — search over 100-token chunks, but give the generator the surrounding ~400-token passage.**

* **Why it fixes Q4.** The failure is in *ranking long, mixed-topic chunks*, and Part A already shows the small-chunk side works: with
  100-token chunks dense search found Q4's answer span at **rank 3**, while with 400-token chunks it fell outside the top 3 (Part A) and
  outside the top 5 for every method (Part B). A 100-token chunk that begins *"One of the most frequent uses of statistics is in testing
  for differences"* has an embedding dominated by that idea, so it matches a question about why statistics are used to analyse experiments.
* **Why not simply switch to 100-token chunks.** They split the Q2 and Q5 spans and give the model too little context for multi-part
  answers (A2.2). Mapping each small hit back to its parent passage keeps the sharp matching of small chunks *and* the context of large
  ones; the cross-encoder then reranks the parents, and the prompt still carries 3 × ~400 tokens, so it fits the same budget.
* **How we would check it.** Re-run the Part B/C hit rates and the Q4 judge verdict. Adding ~100 tokens of overlap between chunks would
  also stop answer spans from being cut at chunk boundaries.

---
## Submission checklist
| Item | Where |
|---|---|
| Answer span for each query | Step 0.2 |
| A1: model, vector size, similarity, batch size, build time | A1.2 table |
| A2: chunk-size table and chosen size | A2.1 table, A2.2 |
| Search comparison table, best method with example | Part B table, B4 |
| Top 3 before/after reranking, reranking table, verdict | C2, C3, C4 |
| Generation prompt, 10 answers, not-found query, generator used | D1.1–D1.3 |
| Judge model, prompt, per-query table, summary counts | D2.1 |
| Spot-check, failure cause, fix | D2.2–D2.4 |

Export: run all cells, then **File → Download → .ipynb** and **File → Print → Save as PDF/HTML**, or in a cell:
`!jupyter nbconvert --to html "/content/drive/MyDrive/<path>/Assignment_2B_RAG_Pipeline.ipynb"`.